{{
  config(
    materialized='table',
    options={
      'default_compression': 'zstd'
    }
  )
}}

SELECT
  "numeroControlePNCP",
  "anoContratacao",
  "dataPublicacaoPNCP",
  "dataAtualizacaoPNCP",
  "horaAtualizacaoPNCP",
  "sequencialOrgao",
  "cnpjOrgao",
  "siglaOrgao",
  "nomeOrgao",
  "sequencialUnidade",
  "codigoUnidade",
  "siglaUnidade",
  "nomeUnidade",
  "codigoEsfera",
  "nomeEsfera",
  "codigoPoder",
  "nomePoder",
  "codigoMunicipio",
  "nomeMunicipio",
  "uf",
  "amparoLegalId",
  "amparoLegalNome",
  "modalidadeId",
  "modalidadeNome",
  "numeroContratacao",
  "processo",
  "objetoContratacao",
  "codigoSituacaoContratacao",
  "nomeSituacaoContratacao",
  "valorTotalEstimado",
  "informacaoComplementar",
  "dataAssinatura",
  "dataVigenciaInicio",
  "dataVigenciaFim",
  "numeroControlePNCPContrato",
  "justificativa",
  "fundamentacaoLegal"
FROM {{ source('bronze', 'pncp_content') }}
