INSERT INTO psa.raw_contratos (
    numero_controle_pncp_compra,
    numero_controle_pncp,
    ano_contrato,
    sequencial_contrato,
    numero_contrato_empenho,
    data_assinatura,
    data_vigencia_inicio,
    data_vigencia_fim,
    data_publicacao_pncp,
    data_atualizacao,
    data_atualizacao_global,
    ni_fornecedor,
    tipo_pessoa,
    nome_razao_social_fornecedor,
    codigo_pais_fornecedor,
    ni_fornecedor_subcontratado,
    nome_fornecedor_subcontratado,
    tipo_pessoa_subcontratada,
    orgao_cnpj,
    orgao_razao_social,
    orgao_poder_id,
    orgao_esfera_id,
    unidade_codigo,
    unidade_nome,
    unidade_uf_sigla,
    unidade_uf_nome,
    unidade_municipio_nome,
    unidade_codigo_ibge,
    orgao_subrogado_cnpj,
    orgao_subrogado_razao_social,
    unidade_subrogada_codigo,
    unidade_subrogada_nome,
    tipo_contrato_id,
    tipo_contrato_nome,
    categoria_processo_id,
    categoria_processo_nome,
    valor_inicial,
    valor_parcela,
    valor_global,
    valor_acumulado,
    numero_parcelas,
    numero_retificacao,
    receita,
    objeto_contrato,
    informacao_complementar,
    processo,
    identificador_cipi,
    url_cipi,
    usuario_nome
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (numero_controle_pncp, ano_contrato, sequencial_contrato) DO UPDATE SET
    numero_controle_pncp_compra = excluded.numero_controle_pncp_compra,
    data_assinatura = excluded.data_assinatura,
    data_vigencia_inicio = excluded.data_vigencia_inicio,
    data_vigencia_fim = excluded.data_vigencia_fim,
    data_publicacao_pncp = excluded.data_publicacao_pncp,
    data_atualizacao = excluded.data_atualizacao,
    data_atualizacao_global = excluded.data_atualizacao_global,
    ni_fornecedor = excluded.ni_fornecedor,
    tipo_pessoa = excluded.tipo_pessoa,
    nome_razao_social_fornecedor = excluded.nome_razao_social_fornecedor,
    codigo_pais_fornecedor = excluded.codigo_pais_fornecedor,
    ni_fornecedor_subcontratado = excluded.ni_fornecedor_subcontratado,
    nome_fornecedor_subcontratado = excluded.nome_fornecedor_subcontratado,
    tipo_pessoa_subcontratada = excluded.tipo_pessoa_subcontratada,
    orgao_cnpj = excluded.orgao_cnpj,
    orgao_razao_social = excluded.orgao_razao_social,
    orgao_poder_id = excluded.orgao_poder_id,
    orgao_esfera_id = excluded.orgao_esfera_id,
    unidade_codigo = excluded.unidade_codigo,
    unidade_nome = excluded.unidade_nome,
    unidade_uf_sigla = excluded.unidade_uf_sigla,
    unidade_uf_nome = excluded.unidade_uf_nome,
    unidade_municipio_nome = excluded.unidade_municipio_nome,
    unidade_codigo_ibge = excluded.unidade_codigo_ibge,
    orgao_subrogado_cnpj = excluded.orgao_subrogado_cnpj,
    orgao_subrogado_razao_social = excluded.orgao_subrogado_razao_social,
    unidade_subrogada_codigo = excluded.unidade_subrogada_codigo,
    unidade_subrogada_nome = excluded.unidade_subrogada_nome,
    tipo_contrato_id = excluded.tipo_contrato_id,
    tipo_contrato_nome = excluded.tipo_contrato_nome,
    categoria_processo_id = excluded.categoria_processo_id,
    categoria_processo_nome = excluded.categoria_processo_nome,
    valor_inicial = excluded.valor_inicial,
    valor_parcela = excluded.valor_parcela,
    valor_global = excluded.valor_global,
    valor_acumulado = excluded.valor_acumulado,
    numero_parcelas = excluded.numero_parcelas,
    numero_retificacao = excluded.numero_retificacao,
    receita = excluded.receita,
    objeto_contrato = excluded.objeto_contrato,
    informacao_complementar = excluded.informacao_complementar,
    processo = excluded.processo,
    identificador_cipi = excluded.identificador_cipi,
    url_cipi = excluded.url_cipi,
    usuario_nome = excluded.usuario_nome,
    extracted_at = CURRENT_TIMESTAMP;
