INSERT INTO psa.raw_atas (
    numero_controle_pncp_ata,
    numero_ata_registro_preco,
    ano_ata,
    numero_controle_pncp_compra,
    cancelado,
    data_cancelamento,
    data_assinatura,
    vigencia_inicio,
    vigencia_fim,
    data_publicacao_pncp,
    data_inclusao,
    data_atualizacao,
    data_atualizacao_global,
    cnpj_orgao,
    nome_orgao,
    codigo_unidade_orgao,
    nome_unidade_orgao,
    cnpj_orgao_subrogado,
    nome_orgao_subrogado,
    codigo_unidade_orgao_subrogado,
    nome_unidade_orgao_subrogado,
    objeto_contratacao,
    usuario
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (numero_controle_pncp_ata) DO UPDATE SET
    numero_ata_registro_preco = excluded.numero_ata_registro_preco,
    ano_ata = excluded.ano_ata,
    numero_controle_pncp_compra = excluded.numero_controle_pncp_compra,
    cancelado = excluded.cancelado,
    data_cancelamento = excluded.data_cancelamento,
    data_assinatura = excluded.data_assinatura,
    vigencia_inicio = excluded.vigencia_inicio,
    vigencia_fim = excluded.vigencia_fim,
    data_publicacao_pncp = excluded.data_publicacao_pncp,
    data_inclusao = excluded.data_inclusao,
    data_atualizacao = excluded.data_atualizacao,
    data_atualizacao_global = excluded.data_atualizacao_global,
    cnpj_orgao = excluded.cnpj_orgao,
    nome_orgao = excluded.nome_orgao,
    codigo_unidade_orgao = excluded.codigo_unidade_orgao,
    nome_unidade_orgao = excluded.nome_unidade_orgao,
    cnpj_orgao_subrogado = excluded.cnpj_orgao_subrogado,
    nome_orgao_subrogado = excluded.nome_orgao_subrogado,
    codigo_unidade_orgao_subrogado = excluded.codigo_unidade_orgao_subrogado,
    nome_unidade_orgao_subrogado = excluded.nome_unidade_orgao_subrogado,
    objeto_contratacao = excluded.objeto_contratacao,
    usuario = excluded.usuario,
    extracted_at = CURRENT_TIMESTAMP;
