INSERT INTO psa.raw_contratacoes (
    numero_controle_pncp,
    ano_compra,
    sequencial_compra,
    numero_compra,
    processo,
    data_inclusao,
    data_publicacao_pncp,
    data_atualizacao,
    data_atualizacao_global,
    data_abertura_proposta,
    data_encerramento_proposta,
    orgao_cnpj,
    orgao_razao_social,
    orgao_poder_id,
    orgao_esfera_id,
    unidade_codigo,
    unidade_nome,
    unidade_uf_sigla,
    unidade_uf_nome,
    unidade_municipio_nome,
    unidade_codigo_ibge,
    orgao_subrogado_cnpj,
    orgao_subrogado_razao_social,
    unidade_subrogada_codigo,
    unidade_subrogada_nome,
    modalidade_id,
    modalidade_nome,
    modo_disputa_id,
    modo_disputa_nome,
    tipo_instrumento_convocatorio_codigo,
    tipo_instrumento_convocatorio_nome,
    amparo_legal_codigo,
    amparo_legal_nome,
    amparo_legal_descricao,
    valor_total_estimado,
    valor_total_homologado,
    situacao_compra_id,
    situacao_compra_nome,
    srp,
    objeto_compra,
    informacao_complementar,
    justificativa_presencial,
    link_sistema_origem,
    link_processo_eletronico,
    usuario_nome
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (numero_controle_pncp) DO UPDATE SET
    ano_compra = excluded.ano_compra,
    sequencial_compra = excluded.sequencial_compra,
    numero_compra = excluded.numero_compra,
    processo = excluded.processo,
    data_inclusao = excluded.data_inclusao,
    data_publicacao_pncp = excluded.data_publicacao_pncp,
    data_atualizacao = excluded.data_atualizacao,
    data_atualizacao_global = excluded.data_atualizacao_global,
    data_abertura_proposta = excluded.data_abertura_proposta,
    data_encerramento_proposta = excluded.data_encerramento_proposta,
    orgao_cnpj = excluded.orgao_cnpj,
    orgao_razao_social = excluded.orgao_razao_social,
    orgao_poder_id = excluded.orgao_poder_id,
    orgao_esfera_id = excluded.orgao_esfera_id,
    unidade_codigo = excluded.unidade_codigo,
    unidade_nome = excluded.unidade_nome,
    unidade_uf_sigla = excluded.unidade_uf_sigla,
    unidade_uf_nome = excluded.unidade_uf_nome,
    unidade_municipio_nome = excluded.unidade_municipio_nome,
    unidade_codigo_ibge = excluded.unidade_codigo_ibge,
    orgao_subrogado_cnpj = excluded.orgao_subrogado_cnpj,
    orgao_subrogado_razao_social = excluded.orgao_subrogado_razao_social,
    unidade_subrogada_codigo = excluded.unidade_subrogada_codigo,
    unidade_subrogada_nome = excluded.unidade_subrogada_nome,
    modalidade_id = excluded.modalidade_id,
    modalidade_nome = excluded.modalidade_nome,
    modo_disputa_id = excluded.modo_disputa_id,
    modo_disputa_nome = excluded.modo_disputa_nome,
    tipo_instrumento_convocatorio_codigo = excluded.tipo_instrumento_convocatorio_codigo,
    tipo_instrumento_convocatorio_nome = excluded.tipo_instrumento_convocatorio_nome,
    amparo_legal_codigo = excluded.amparo_legal_codigo,
    amparo_legal_nome = excluded.amparo_legal_nome,
    amparo_legal_descricao = excluded.amparo_legal_descricao,
    valor_total_estimado = excluded.valor_total_estimado,
    valor_total_homologado = excluded.valor_total_homologado,
    situacao_compra_id = excluded.situacao_compra_id,
    situacao_compra_nome = excluded.situacao_compra_nome,
    srp = excluded.srp,
    objeto_compra = excluded.objeto_compra,
    informacao_complementar = excluded.informacao_complementar,
    justificativa_presencial = excluded.justificativa_presencial,
    link_sistema_origem = excluded.link_sistema_origem,
    link_processo_eletronico = excluded.link_processo_eletronico,
    usuario_nome = excluded.usuario_nome,
    extracted_at = CURRENT_TIMESTAMP;
