// Copyright 2026 claude. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package types

import "encoding/json"

type AtaRegistroPrecoPeriodoDTO struct {
	AnoAta                      int    `json:"anoAta"`
	Cancelado                   bool   `json:"cancelado"`
	CnpjOrgao                   string `json:"cnpjOrgao"`
	CnpjOrgaoSubrogado          string `json:"cnpjOrgaoSubrogado"`
	CodigoUnidadeOrgao          string `json:"codigoUnidadeOrgao"`
	CodigoUnidadeOrgaoSubrogado string `json:"codigoUnidadeOrgaoSubrogado"`
	DataAssinatura              string `json:"dataAssinatura"`
	DataAtualizacao             string `json:"dataAtualizacao"`
	DataAtualizacaoGlobal       string `json:"dataAtualizacaoGlobal"`
	DataCancelamento            string `json:"dataCancelamento"`
	DataInclusao                string `json:"dataInclusao"`
	DataPublicacaoPncp          string `json:"dataPublicacaoPncp"`
	NomeOrgao                   string `json:"nomeOrgao"`
	NomeOrgaoSubrogado          string `json:"nomeOrgaoSubrogado"`
	NomeUnidadeOrgao            string `json:"nomeUnidadeOrgao"`
	NomeUnidadeOrgaoSubrogado   string `json:"nomeUnidadeOrgaoSubrogado"`
	NumeroAtaRegistroPreco      string `json:"numeroAtaRegistroPreco"`
	NumeroControlePNCPAta       string `json:"numeroControlePNCPAta"`
	NumeroControlePNCPCompra    string `json:"numeroControlePNCPCompra"`
	ObjetoContratacao           string `json:"objetoContratacao"`
	PossibilidadeAdesao         bool   `json:"possibilidadeAdesao"`
	Usuario                     string `json:"usuario"`
	VigenciaFim                 string `json:"vigenciaFim"`
	VigenciaInicio              string `json:"vigenciaInicio"`
}

type Categoria struct {
	Id   int    `json:"id"`
	Nome string `json:"nome"`
}

type ConsultarInstrumentoCobrancaDTO struct {
	Ano                           int             `json:"ano"`
	ChaveNFe                      string          `json:"chaveNFe"`
	Cnpj                          string          `json:"cnpj"`
	DataAtualizacao               string          `json:"dataAtualizacao"`
	DataConsultaNFe               string          `json:"dataConsultaNFe"`
	DataEmissaoDocumento          string          `json:"dataEmissaoDocumento"`
	DataInclusao                  string          `json:"dataInclusao"`
	FonteNFe                      int             `json:"fonteNFe"`
	JsonResponseNFe               string          `json:"jsonResponseNFe"`
	NotaFiscalEletronica          json.RawMessage `json:"notaFiscalEletronica"`
	NumeroInstrumentoCobranca     string          `json:"numeroInstrumentoCobranca"`
	Observacao                    string          `json:"observacao"`
	RecuperarContratoDTO          json.RawMessage `json:"recuperarContratoDTO"`
	SequencialContrato            int             `json:"sequencialContrato"`
	SequencialInstrumentoCobranca int             `json:"sequencialInstrumentoCobranca"`
	StatusResponseNFe             string          `json:"statusResponseNFe"`
	TipoInstrumentoCobranca       json.RawMessage `json:"tipoInstrumentoCobranca"`
}

type ContratacaoFonteOrcamentariaDTO struct {
	Codigo       int    `json:"codigo"`
	DataInclusao string `json:"dataInclusao"`
	Descricao    string `json:"descricao"`
	Nome         string `json:"nome"`
}

type EventoNotaFiscalConsultaDTO struct {
	DataEvento   string `json:"dataEvento"`
	Evento       string `json:"evento"`
	MotivoEvento string `json:"motivoEvento"`
	TipoEvento   string `json:"tipoEvento"`
}

type ItemNotaFiscalConsultaDTO struct {
	Cfop                    string `json:"cfop"`
	CodigoNCM               string `json:"codigoNCM"`
	DescricaoNCM            string `json:"descricaoNCM"`
	DescricaoProdutoServico string `json:"descricaoProdutoServico"`
	NumeroItem              string `json:"numeroItem"`
	Quantidade              string `json:"quantidade"`
	Unidade                 string `json:"unidade"`
	ValorTotal              string `json:"valorTotal"`
	ValorUnitario           string `json:"valorUnitario"`
}

type NotaFiscalEletronicaConsultaDTO struct {
	Chave                           string          `json:"chave"`
	CodigoOrgaoDestinatario         string          `json:"codigoOrgaoDestinatario"`
	CodigoOrgaoSuperiorDestinatario string          `json:"codigoOrgaoSuperiorDestinatario"`
	DataAtualizacao                 string          `json:"dataAtualizacao"`
	DataEmissao                     string          `json:"dataEmissao"`
	DataInclusao                    string          `json:"dataInclusao"`
	DataTipoEventoMaisRecente       string          `json:"dataTipoEventoMaisRecente"`
	Eventos                         json.RawMessage `json:"eventos"`
	InstrumentoCobrancaId           int             `json:"instrumentoCobrancaId"`
	Itens                           json.RawMessage `json:"itens"`
	NfTransparenciaID               int             `json:"nfTransparenciaID"`
	NiEmitente                      string          `json:"niEmitente"`
	NomeEmitente                    string          `json:"nomeEmitente"`
	NomeMunicipioEmitente           string          `json:"nomeMunicipioEmitente"`
	NomeOrgaoDestinatario           string          `json:"nomeOrgaoDestinatario"`
	NomeOrgaoSuperiorDestinatario   string          `json:"nomeOrgaoSuperiorDestinatario"`
	Numero                          int             `json:"numero"`
	Serie                           int             `json:"serie"`
	TipoEventoMaisRecente           string          `json:"tipoEventoMaisRecente"`
	ValorNotaFiscal                 string          `json:"valorNotaFiscal"`
}

type PaginaRetornoAtaRegistroPrecoPeriodoDTO struct {
	Data             json.RawMessage `json:"data"`
	Empty            bool            `json:"empty"`
	NumeroPagina     int             `json:"numeroPagina"`
	PaginasRestantes int             `json:"paginasRestantes"`
	TotalPaginas     int             `json:"totalPaginas"`
	TotalRegistros   int             `json:"totalRegistros"`
}

type PaginaRetornoConsultarInstrumentoCobrancaDTO struct {
	Data             json.RawMessage `json:"data"`
	Empty            bool            `json:"empty"`
	NumeroPagina     int             `json:"numeroPagina"`
	PaginasRestantes int             `json:"paginasRestantes"`
	TotalPaginas     int             `json:"totalPaginas"`
	TotalRegistros   int             `json:"totalRegistros"`
}

type PaginaRetornoPlanoContratacaoComItensDoUsuarioDTO struct {
	Data             json.RawMessage `json:"data"`
	Empty            bool            `json:"empty"`
	NumeroPagina     int             `json:"numeroPagina"`
	PaginasRestantes int             `json:"paginasRestantes"`
	TotalPaginas     int             `json:"totalPaginas"`
	TotalRegistros   int             `json:"totalRegistros"`
}

type PaginaRetornoRecuperarCompraPublicacaoDTO struct {
	Data             json.RawMessage `json:"data"`
	Empty            bool            `json:"empty"`
	NumeroPagina     int             `json:"numeroPagina"`
	PaginasRestantes int             `json:"paginasRestantes"`
	TotalPaginas     int             `json:"totalPaginas"`
	TotalRegistros   int             `json:"totalRegistros"`
}

type PaginaRetornoRecuperarContratoDTO struct {
	Data             json.RawMessage `json:"data"`
	Empty            bool            `json:"empty"`
	NumeroPagina     int             `json:"numeroPagina"`
	PaginasRestantes int             `json:"paginasRestantes"`
	TotalPaginas     int             `json:"totalPaginas"`
	TotalRegistros   int             `json:"totalRegistros"`
}

type PlanoContratacaoComItensDoUsuarioDTO struct {
	AnoPca                   int             `json:"anoPca"`
	CodigoUnidade            string          `json:"codigoUnidade"`
	DataAtualizacaoGlobalPCA string          `json:"dataAtualizacaoGlobalPCA"`
	DataPublicacaoPNCP       string          `json:"dataPublicacaoPNCP"`
	IdPcaPncp                string          `json:"idPcaPncp"`
	Itens                    json.RawMessage `json:"itens"`
	NomeUnidade              string          `json:"nomeUnidade"`
	OrgaoEntidadeCnpj        string          `json:"orgaoEntidadeCnpj"`
	OrgaoEntidadeRazaoSocial string          `json:"orgaoEntidadeRazaoSocial"`
}

type PlanoContratacaoItemDTO struct {
	CategoriaItemPcaNome        string  `json:"categoriaItemPcaNome"`
	ClassificacaoCatalogoId     int     `json:"classificacaoCatalogoId"`
	ClassificacaoSuperiorCodigo string  `json:"classificacaoSuperiorCodigo"`
	ClassificacaoSuperiorNome   string  `json:"classificacaoSuperiorNome"`
	CodigoItem                  string  `json:"codigoItem"`
	DataAtualizacao             string  `json:"dataAtualizacao"`
	DataDesejada                string  `json:"dataDesejada"`
	DataInclusao                string  `json:"dataInclusao"`
	DescricaoItem               string  `json:"descricaoItem"`
	GrupoContratacaoCodigo      string  `json:"grupoContratacaoCodigo"`
	GrupoContratacaoNome        string  `json:"grupoContratacaoNome"`
	NomeClassificacaoCatalogo   string  `json:"nomeClassificacaoCatalogo"`
	NumeroItem                  int     `json:"numeroItem"`
	PdmCodigo                   string  `json:"pdmCodigo"`
	PdmDescricao                string  `json:"pdmDescricao"`
	QuantidadeEstimada          float64 `json:"quantidadeEstimada"`
	UnidadeFornecimento         string  `json:"unidadeFornecimento"`
	UnidadeRequisitante         string  `json:"unidadeRequisitante"`
	ValorOrcamentoExercicio     float64 `json:"valorOrcamentoExercicio"`
	ValorTotal                  float64 `json:"valorTotal"`
	ValorUnitario               float64 `json:"valorUnitario"`
}

type RecuperarAmparoLegalDTO struct {
	Codigo    int    `json:"codigo"`
	Descricao string `json:"descricao"`
	Nome      string `json:"nome"`
}

type RecuperarCompraDTO struct {
	AmparoLegal                       json.RawMessage `json:"amparoLegal"`
	AnoCompra                         int             `json:"anoCompra"`
	DataAberturaProposta              string          `json:"dataAberturaProposta"`
	DataAtualizacao                   string          `json:"dataAtualizacao"`
	DataAtualizacaoGlobal             string          `json:"dataAtualizacaoGlobal"`
	DataEncerramentoProposta          string          `json:"dataEncerramentoProposta"`
	DataInclusao                      string          `json:"dataInclusao"`
	DataPublicacaoPncp                string          `json:"dataPublicacaoPncp"`
	EmendaParlamentar                 bool            `json:"emendaParlamentar"`
	ExisteResultado                   bool            `json:"existeResultado"`
	FontesOrcamentarias               json.RawMessage `json:"fontesOrcamentarias"`
	IndicadorOrcamentoSigiloso        string          `json:"indicadorOrcamentoSigiloso"`
	InformacaoComplementar            string          `json:"informacaoComplementar"`
	JustificativaPresencial           string          `json:"justificativaPresencial"`
	LinkProcessoEletronico            string          `json:"linkProcessoEletronico"`
	LinkSistemaOrigem                 string          `json:"linkSistemaOrigem"`
	ModalidadeId                      int             `json:"modalidadeId"`
	ModalidadeNome                    string          `json:"modalidadeNome"`
	ModoDisputaId                     int             `json:"modoDisputaId"`
	ModoDisputaNome                   string          `json:"modoDisputaNome"`
	NumeroCompra                      string          `json:"numeroCompra"`
	NumeroControlePNCP                string          `json:"numeroControlePNCP"`
	ObjetoCompra                      string          `json:"objetoCompra"`
	OrcamentoSigilosoCodigo           int             `json:"orcamentoSigilosoCodigo"`
	OrcamentoSigilosoDescricao        string          `json:"orcamentoSigilosoDescricao"`
	OrgaoEntidade                     json.RawMessage `json:"orgaoEntidade"`
	OrgaoSubRogado                    json.RawMessage `json:"orgaoSubRogado"`
	Processo                          string          `json:"processo"`
	SequencialCompra                  int             `json:"sequencialCompra"`
	SituacaoCompraId                  string          `json:"situacaoCompraId"`
	SituacaoCompraNome                string          `json:"situacaoCompraNome"`
	Srp                               bool            `json:"srp"`
	TipoInstrumentoConvocatorioCodigo int             `json:"tipoInstrumentoConvocatorioCodigo"`
	TipoInstrumentoConvocatorioNome   string          `json:"tipoInstrumentoConvocatorioNome"`
	UnidadeOrgao                      json.RawMessage `json:"unidadeOrgao"`
	UnidadeSubRogada                  json.RawMessage `json:"unidadeSubRogada"`
	UsuarioNome                       string          `json:"usuarioNome"`
	ValorTotalEstimado                float64         `json:"valorTotalEstimado"`
	ValorTotalHomologado              float64         `json:"valorTotalHomologado"`
}

type RecuperarCompraPublicacaoDTO struct {
	AmparoLegal                       json.RawMessage `json:"amparoLegal"`
	AnoCompra                         int             `json:"anoCompra"`
	DataAberturaProposta              string          `json:"dataAberturaProposta"`
	DataAtualizacao                   string          `json:"dataAtualizacao"`
	DataAtualizacaoGlobal             string          `json:"dataAtualizacaoGlobal"`
	DataEncerramentoProposta          string          `json:"dataEncerramentoProposta"`
	DataInclusao                      string          `json:"dataInclusao"`
	DataPublicacaoPncp                string          `json:"dataPublicacaoPncp"`
	EmendaParlamentar                 bool            `json:"emendaParlamentar"`
	FontesOrcamentarias               json.RawMessage `json:"fontesOrcamentarias"`
	InformacaoComplementar            string          `json:"informacaoComplementar"`
	JustificativaPresencial           string          `json:"justificativaPresencial"`
	LinkProcessoEletronico            string          `json:"linkProcessoEletronico"`
	LinkSistemaOrigem                 string          `json:"linkSistemaOrigem"`
	ModalidadeId                      int             `json:"modalidadeId"`
	ModalidadeNome                    string          `json:"modalidadeNome"`
	ModoDisputaId                     int             `json:"modoDisputaId"`
	ModoDisputaNome                   string          `json:"modoDisputaNome"`
	NumeroCompra                      string          `json:"numeroCompra"`
	NumeroControlePNCP                string          `json:"numeroControlePNCP"`
	ObjetoCompra                      string          `json:"objetoCompra"`
	OrgaoEntidade                     json.RawMessage `json:"orgaoEntidade"`
	OrgaoSubRogado                    json.RawMessage `json:"orgaoSubRogado"`
	Processo                          string          `json:"processo"`
	SequencialCompra                  int             `json:"sequencialCompra"`
	SituacaoCompraId                  string          `json:"situacaoCompraId"`
	SituacaoCompraNome                string          `json:"situacaoCompraNome"`
	Srp                               bool            `json:"srp"`
	TipoInstrumentoConvocatorioCodigo int             `json:"tipoInstrumentoConvocatorioCodigo"`
	TipoInstrumentoConvocatorioNome   string          `json:"tipoInstrumentoConvocatorioNome"`
	UnidadeOrgao                      json.RawMessage `json:"unidadeOrgao"`
	UnidadeSubRogada                  json.RawMessage `json:"unidadeSubRogada"`
	UsuarioNome                       string          `json:"usuarioNome"`
	ValorTotalEstimado                float64         `json:"valorTotalEstimado"`
	ValorTotalHomologado              float64         `json:"valorTotalHomologado"`
}

type RecuperarContratoDTO struct {
	AnoContrato                 int             `json:"anoContrato"`
	CategoriaProcesso           json.RawMessage `json:"categoriaProcesso"`
	CodigoPaisFornecedor        string          `json:"codigoPaisFornecedor"`
	DataAssinatura              string          `json:"dataAssinatura"`
	DataAtualizacao             string          `json:"dataAtualizacao"`
	DataAtualizacaoGlobal       string          `json:"dataAtualizacaoGlobal"`
	DataPublicacaoPncp          string          `json:"dataPublicacaoPncp"`
	DataVigenciaFim             string          `json:"dataVigenciaFim"`
	DataVigenciaInicio          string          `json:"dataVigenciaInicio"`
	EmendaParlamentar           bool            `json:"emendaParlamentar"`
	FrutoAdesao                 bool            `json:"frutoAdesao"`
	IdentificadorCipi           string          `json:"identificadorCipi"`
	InformacaoComplementar      string          `json:"informacaoComplementar"`
	NiFornecedor                string          `json:"niFornecedor"`
	NiFornecedorSubContratado   string          `json:"niFornecedorSubContratado"`
	NomeFornecedorSubContratado string          `json:"nomeFornecedorSubContratado"`
	NomeRazaoSocialFornecedor   string          `json:"nomeRazaoSocialFornecedor"`
	NumeroContratoEmpenho       string          `json:"numeroContratoEmpenho"`
	NumeroControlePNCP          string          `json:"numeroControlePNCP"`
	NumeroControlePncpAta       string          `json:"numeroControlePncpAta"`
	NumeroControlePncpCompra    string          `json:"numeroControlePncpCompra"`
	NumeroParcelas              int             `json:"numeroParcelas"`
	NumeroRetificacao           int             `json:"numeroRetificacao"`
	ObjetoContrato              string          `json:"objetoContrato"`
	OrgaoEntidade               json.RawMessage `json:"orgaoEntidade"`
	OrgaoSubRogado              json.RawMessage `json:"orgaoSubRogado"`
	Processo                    string          `json:"processo"`
	Receita                     bool            `json:"receita"`
	SequencialContrato          int             `json:"sequencialContrato"`
	TemRemanejamento            bool            `json:"temRemanejamento"`
	TipoContrato                json.RawMessage `json:"tipoContrato"`
	TipoPessoa                  string          `json:"tipoPessoa"`
	TipoPessoaSubContratada     string          `json:"tipoPessoaSubContratada"`
	UnidadeOrgao                json.RawMessage `json:"unidadeOrgao"`
	UnidadeSubRogada            json.RawMessage `json:"unidadeSubRogada"`
	UrlCipi                     string          `json:"urlCipi"`
	UsuarioNome                 string          `json:"usuarioNome"`
	ValorAcumulado              float64         `json:"valorAcumulado"`
	ValorGlobal                 float64         `json:"valorGlobal"`
	ValorInicial                float64         `json:"valorInicial"`
	ValorParcela                float64         `json:"valorParcela"`
}

type RecuperarOrgaoEntidadeDTO struct {
	Cnpj        string `json:"cnpj"`
	EsferaId    string `json:"esferaId"`
	PoderId     string `json:"poderId"`
	RazaoSocial string `json:"razaoSocial"`
}

type RecuperarUnidadeOrgaoDTO struct {
	CodigoIbge    string `json:"codigoIbge"`
	CodigoUnidade string `json:"codigoUnidade"`
	MunicipioNome string `json:"municipioNome"`
	NomeUnidade   string `json:"nomeUnidade"`
	UfNome        string `json:"ufNome"`
	UfSigla       string `json:"ufSigla"`
}

type RespostaErroValidacaoDTO struct {
	Error     string `json:"error"`
	Message   string `json:"message"`
	Path      string `json:"path"`
	Status    string `json:"status"`
	Timestamp string `json:"timestamp"`
}

type TipoContrato struct {
	Id   int    `json:"id"`
	Nome string `json:"nome"`
}

type TipoInstrumentoCobrancaDTO struct {
	DataAtualizacao string `json:"dataAtualizacao"`
	DataInclusao    string `json:"dataInclusao"`
	Descricao       string `json:"descricao"`
	Id              int    `json:"id"`
	Nome            string `json:"nome"`
	StatusAtivo     bool   `json:"statusAtivo"`
}
