site_name: BALIZA
site_description: 'Backup Aberto de Licitações Zelando pelo Acesso - Historical archive of Brazilian public procurement data'
site_author: 'Franklin Baldo'
site_url: 'https://franklinbaldo.github.io/baliza/'

repo_name: 'franklinbaldo/baliza'
repo_url: 'https://github.com/franklinbaldo/baliza'
edit_uri: 'edit/main/docs/'

theme:
  name: material
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  icon:
    repo: fontawesome/brands/github-alt

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/franklinbaldo
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/franklinbaldo/

plugins:
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - search

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
