[project]
name = "baliza"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "requests",
    "tenacity",
    "zstandard",
    "internetarchive",
    "typer[all]",
    "duckdb", # Native Parquet support
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-mock",
]
