[project]
name = "baliza"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "requests",
    "tenacity",
    "internetarchive",
    "typer[all]",
    "duckdb", # Native Parquet support with built-in compression
]

[project.optional-dependencies]
analytics = [
    "dbt-duckdb",  # DBT adapter for DuckDB
    "dbt-core",
]
dev = [
    "pytest",
    "pytest-mock",
]

[dependency-groups]
dev = [
    "nbformat>=5.10.4",
    "pytest>=8.4.1",
    "pytest-mock>=3.14.1",
]
