name: 'dbt_baliza'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'baliza'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

# Configuring models
models:
  dbt_baliza:
    # Planning layer - Task planning for dbt-driven extraction
    planning:
      +materialized: "{{ 'table' if target.name == 'prod' else 'view' }}"
      +schema: planning
    
    # Runtime layer - Execution tracking (read-only from dbt perspective)
    runtime:
      +materialized: view
      +schema: runtime
    
    # Analytics layer - Monitoring and reporting views
    analytics:
      +materialized: view
      +schema: analytics
    
    # Bronze layer - Incremental by default for performance
    bronze:
      +materialized: incremental
      +schema: bronze
    
    # Silver layer - Incremental by default for performance
    silver:
      +materialized: incremental
      +schema: silver
    
    # Gold layer - Incremental for faster rebuilds on large datasets
    gold:
      +materialized: incremental
      +schema: gold

# Variables
vars:
  data_dir: "{{ env_var('DATA_DIR', '../data') }}"
  psa_schema: "{{ env_var('PSA_SCHEMA', 'psa') }}"
  
  # Date range for processing (can be overridden at runtime)
  start_date: "{{ env_var('START_DATE', '2024-01-01') }}"
  end_date: "{{ env_var('END_DATE', '2024-12-31') }}"
  task_status_values: ['PENDING', 'CLAIMED', 'COMPLETED', 'FAILED']
  environment_values: ['dev', 'staging', 'prod']

# Tests
tests:
  +schema: "{{ target.schema }}_tests"

# Snapshots
snapshots:
  +schema: "{{ target.schema }}_snapshots"

# Seeds
seeds:
  +schema: psa