# DBT profiles for Baliza project
baliza:
  outputs:
    dev:
      type: duckdb
      path: '../state/baliza_dbt.duckdb'
      extensions:
        - json    # For JSON processing in raw data
      settings:
        max_memory: '2GB'
        threads: 4
    
    prod:
      type: duckdb
      path: '../state/baliza_prod.duckdb'
      extensions:
        - json
      settings:
        max_memory: '4GB'
        threads: 8
  
  target: dev