version: 2

sources:
  - name: pncp_domain_tables
    description: "Official PNCP domain tables extracted from Manual PNCP Consultas Versão 1"
    meta:
      source_document: "docs/openapi/MANUAL-PNCP-CONSULSTAS-VERSAO-1.md"
      extraction_date: "2025-01-22"

seeds:
  - name: call_instrument
    description: "Instrumento Convocatório - Seção 5.1 do Manual PNCP"
    meta:
      manual_section: "5.1"
      manual_line: 152
      total_records: 3
    columns:
      - name: code
        description: "Código oficial do instrumento conforme manual PNCP"
        tests:
          - unique
          - not_null
      - name: description
        description: "Descrição oficial do instrumento conforme manual PNCP"

  - name: contracting_modality
    description: "Modalidade de Contratação - Seção 5.2 do Manual PNCP"
    meta:
      manual_section: "5.2"
      manual_line: 158
      total_records: 13
    columns:
      - name: code
        description: "Código oficial da modalidade conforme manual PNCP"
        tests:
          - unique
          - not_null
      - name: description
        description: "Descrição oficial da modalidade conforme manual PNCP"

  - name: bidding_mode
    description: "Modo de Disputa - Seção 5.3 do Manual PNCP"
    meta:
      manual_section: "5.3"
      manual_line: 174
      total_records: 6
    columns:
      - name: code
        description: "Código oficial do modo conforme manual PNCP"
        tests:
          - unique
          - not_null
      - name: description
        description: "Descrição oficial do modo conforme manual PNCP"

  - name: judgment_criteria
    description: "Critério de Julgamento - Seção 5.4 do Manual PNCP"
    meta:
      manual_section: "5.4"
      manual_line: 183
      total_records: 8
    columns:
      - name: code
        description: "Código oficial do critério conforme manual PNCP"
        tests:
          - unique
          - not_null
      - name: description
        description: "Descrição oficial do critério conforme manual PNCP"

  - name: contracting_situation
    description: "Situação da Contratação - Seção 5.5 do Manual PNCP"
    meta:
      manual_section: "5.5"
      manual_line: 196
      total_records: 4
    columns:
      - name: code
        description: "Código oficial da situação conforme manual PNCP"
        tests:
          - unique
          - not_null
      - name: description
        description: "Descrição oficial da situação conforme manual PNCP"

  - name: item_situation
    description: "Situação do Item da Contratação - Seção 5.6 do Manual PNCP"
    meta:
      manual_section: "5.6"
      manual_line: 205
      total_records: 5
    columns:
      - name: code
        description: "Código oficial da situação conforme manual PNCP"
        tests:
          - unique
          - not_null
      - name: description
        description: "Descrição oficial da situação conforme manual PNCP"

  - name: benefit_type
    description: "Tipo de Benefício - Seção 5.7 do Manual PNCP"
    meta:
      manual_section: "5.7"
      manual_line: 215
      total_records: 5
    columns:
      - name: code
        description: "Código oficial do benefício conforme manual PNCP"
        tests:
          - unique
          - not_null
      - name: description
        description: "Descrição oficial do benefício conforme manual PNCP"

  - name: result_situation
    description: "Situação do Resultado do Item da Contratação - Seção 5.8 do Manual PNCP"
    meta:
      manual_section: "5.8"
      manual_line: 225
      total_records: 2
    columns:
      - name: code
        description: "Código oficial da situação conforme manual PNCP"
        tests:
          - unique
          - not_null
      - name: description
        description: "Descrição oficial da situação conforme manual PNCP"

  - name: contract_type
    description: "Tipo de Contrato - Seção 5.9 do Manual PNCP"
    meta:
      manual_section: "5.9"
      manual_line: 232
      total_records: 12
    columns:
      - name: code
        description: "Código oficial do tipo conforme manual PNCP"
        tests:
          - unique
          - not_null
      - name: description
        description: "Descrição oficial do tipo conforme manual PNCP"

  - name: contract_term_type
    description: "Tipo de Termo de Contrato - Seção 5.10 do Manual PNCP"
    meta:
      manual_section: "5.10"
      manual_line: 249
      total_records: 3
    columns:
      - name: code
        description: "Código oficial do termo conforme manual PNCP"
        tests:
          - unique
          - not_null
      - name: description
        description: "Descrição oficial do termo conforme manual PNCP"

  - name: process_category
    description: "Categoria do Processo - Seção 5.11 do Manual PNCP"
    meta:
      manual_section: "5.11"
      manual_line: 257
      total_records: 11
    columns:
      - name: code
        description: "Código oficial da categoria conforme manual PNCP"
        tests:
          - unique
          - not_null
      - name: description
        description: "Descrição oficial da categoria conforme manual PNCP"