// Copyright 2026 claude. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package mcp

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	mcplib "github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"
	"pncp-pp-cli/internal/cli"
	"pncp-pp-cli/internal/client"
	"pncp-pp-cli/internal/cliutil"
	"pncp-pp-cli/internal/config"
	"pncp-pp-cli/internal/mcp/cobratree"
	"pncp-pp-cli/internal/store"
)

// RegisterTools registers all API operations as MCP tools.
func RegisterTools(s *server.MCPServer) {
	s.AddTool(
		mcplib.NewTool("atas_consultar-registro-preco-data-atualizacao",
			mcplib.WithDescription("Consultar Atas de Registro de Preço por Data de Atualização Global. Required: dataInicial, dataFinal. Optional: idUsuario, cnpj, codigoUnidadeAdministrativa. Returns array of AtaRegistroPrecoPeriodoDto."),
			mcplib.WithString("dataInicial", mcplib.Required(), mcplib.Description("Formato: yyyyMMdd")),
			mcplib.WithString("dataFinal", mcplib.Required(), mcplib.Description("Formato: yyyyMMdd")),
			mcplib.WithString("idUsuario", mcplib.Description("Id usuario")),
			mcplib.WithString("cnpj", mcplib.Description("Cnpj")),
			mcplib.WithString("codigoUnidadeAdministrativa", mcplib.Description("Codigo unidade administrativa")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/v1/atas/atualizacao", []mcpParamBinding{{PublicName: "dataInicial", WireName: "dataInicial", Location: "query"}, {PublicName: "dataFinal", WireName: "dataFinal", Location: "query"}, {PublicName: "idUsuario", WireName: "idUsuario", Location: "query"}, {PublicName: "cnpj", WireName: "cnpj", Location: "query"}, {PublicName: "codigoUnidadeAdministrativa", WireName: "codigoUnidadeAdministrativa", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("atas_consultar-registro-preco-periodo",
			mcplib.WithDescription("Consultar Ata de Registro de Preço por Período de Vigência. Required: dataInicial, dataFinal. Optional: idUsuario, cnpj, codigoUnidadeAdministrativa. Returns array of AtaRegistroPrecoPeriodoDto."),
			mcplib.WithString("dataInicial", mcplib.Required(), mcplib.Description("Formato: yyyyMMdd")),
			mcplib.WithString("dataFinal", mcplib.Required(), mcplib.Description("Formato: yyyyMMdd")),
			mcplib.WithString("idUsuario", mcplib.Description("Id usuario")),
			mcplib.WithString("cnpj", mcplib.Description("Cnpj")),
			mcplib.WithString("codigoUnidadeAdministrativa", mcplib.Description("Codigo unidade administrativa")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/v1/atas", []mcpParamBinding{{PublicName: "dataInicial", WireName: "dataInicial", Location: "query"}, {PublicName: "dataFinal", WireName: "dataFinal", Location: "query"}, {PublicName: "idUsuario", WireName: "idUsuario", Location: "query"}, {PublicName: "cnpj", WireName: "cnpj", Location: "query"}, {PublicName: "codigoUnidadeAdministrativa", WireName: "codigoUnidadeAdministrativa", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("contratacoes_consultar-contratacao-periodo-recebimento-propostas",
			mcplib.WithDescription("Consultar Contratações com Recebimento de Propostas Aberto. Required: dataFinal. Optional: codigoModalidadeContratacao, uf, codigoMunicipioIbge (plus 3 more). Returns array of RecuperarCompraPublicacaoDto."),
			mcplib.WithString("dataFinal", mcplib.Required(), mcplib.Description("Data final")),
			mcplib.WithString("codigoModalidadeContratacao", mcplib.Description("Codigo modalidade contratacao")),
			mcplib.WithString("uf", mcplib.Description("Uf")),
			mcplib.WithString("codigoMunicipioIbge", mcplib.Description("Codigo municipio ibge")),
			mcplib.WithString("cnpj", mcplib.Description("Cnpj")),
			mcplib.WithString("codigoUnidadeAdministrativa", mcplib.Description("Codigo unidade administrativa")),
			mcplib.WithString("idUsuario", mcplib.Description("Id usuario")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/v1/contratacoes/proposta", []mcpParamBinding{{PublicName: "dataFinal", WireName: "dataFinal", Location: "query"}, {PublicName: "codigoModalidadeContratacao", WireName: "codigoModalidadeContratacao", Location: "query"}, {PublicName: "uf", WireName: "uf", Location: "query"}, {PublicName: "codigoMunicipioIbge", WireName: "codigoMunicipioIbge", Location: "query"}, {PublicName: "cnpj", WireName: "cnpj", Location: "query"}, {PublicName: "codigoUnidadeAdministrativa", WireName: "codigoUnidadeAdministrativa", Location: "query"}, {PublicName: "idUsuario", WireName: "idUsuario", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("contratacoes_consultar-contratacao-por-data-de-publicacao",
			mcplib.WithDescription("Consultar Contratações por Data de Publicação. Required: dataInicial, dataFinal, codigoModalidadeContratacao. Optional: codigoModoDisputa, uf, codigoMunicipioIbge (plus 3 more). Returns array of RecuperarCompraPublicacaoDto."),
			mcplib.WithString("dataInicial", mcplib.Required(), mcplib.Description("Data inicial")),
			mcplib.WithString("dataFinal", mcplib.Required(), mcplib.Description("Data final")),
			mcplib.WithString("codigoModalidadeContratacao", mcplib.Required(), mcplib.Description("Codigo modalidade contratacao")),
			mcplib.WithString("codigoModoDisputa", mcplib.Description("Codigo modo disputa")),
			mcplib.WithString("uf", mcplib.Description("Uf")),
			mcplib.WithString("codigoMunicipioIbge", mcplib.Description("Codigo municipio ibge")),
			mcplib.WithString("cnpj", mcplib.Description("Cnpj")),
			mcplib.WithString("codigoUnidadeAdministrativa", mcplib.Description("Codigo unidade administrativa")),
			mcplib.WithString("idUsuario", mcplib.Description("Id usuario")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/v1/contratacoes/publicacao", []mcpParamBinding{{PublicName: "dataInicial", WireName: "dataInicial", Location: "query"}, {PublicName: "dataFinal", WireName: "dataFinal", Location: "query"}, {PublicName: "codigoModalidadeContratacao", WireName: "codigoModalidadeContratacao", Location: "query"}, {PublicName: "codigoModoDisputa", WireName: "codigoModoDisputa", Location: "query"}, {PublicName: "uf", WireName: "uf", Location: "query"}, {PublicName: "codigoMunicipioIbge", WireName: "codigoMunicipioIbge", Location: "query"}, {PublicName: "cnpj", WireName: "cnpj", Location: "query"}, {PublicName: "codigoUnidadeAdministrativa", WireName: "codigoUnidadeAdministrativa", Location: "query"}, {PublicName: "idUsuario", WireName: "idUsuario", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("contratacoes_consultar-contratacao-por-data-ultima-atualizacao",
			mcplib.WithDescription("Consultar Contratações por Data de Atualização Global. Required: dataInicial, dataFinal, codigoModalidadeContratacao. Optional: codigoModoDisputa, uf, codigoMunicipioIbge (plus 3 more). Returns array of RecuperarCompraPublicacaoDto."),
			mcplib.WithString("dataInicial", mcplib.Required(), mcplib.Description("Data inicial")),
			mcplib.WithString("dataFinal", mcplib.Required(), mcplib.Description("Data final")),
			mcplib.WithString("codigoModalidadeContratacao", mcplib.Required(), mcplib.Description("Codigo modalidade contratacao")),
			mcplib.WithString("codigoModoDisputa", mcplib.Description("Codigo modo disputa")),
			mcplib.WithString("uf", mcplib.Description("Uf")),
			mcplib.WithString("codigoMunicipioIbge", mcplib.Description("Codigo municipio ibge")),
			mcplib.WithString("cnpj", mcplib.Description("Cnpj")),
			mcplib.WithString("codigoUnidadeAdministrativa", mcplib.Description("Codigo unidade administrativa")),
			mcplib.WithString("idUsuario", mcplib.Description("Id usuario")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/v1/contratacoes/atualizacao", []mcpParamBinding{{PublicName: "dataInicial", WireName: "dataInicial", Location: "query"}, {PublicName: "dataFinal", WireName: "dataFinal", Location: "query"}, {PublicName: "codigoModalidadeContratacao", WireName: "codigoModalidadeContratacao", Location: "query"}, {PublicName: "codigoModoDisputa", WireName: "codigoModoDisputa", Location: "query"}, {PublicName: "uf", WireName: "uf", Location: "query"}, {PublicName: "codigoMunicipioIbge", WireName: "codigoMunicipioIbge", Location: "query"}, {PublicName: "cnpj", WireName: "cnpj", Location: "query"}, {PublicName: "codigoUnidadeAdministrativa", WireName: "codigoUnidadeAdministrativa", Location: "query"}, {PublicName: "idUsuario", WireName: "idUsuario", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("contratos_consultar-por-data-atualizacao-global",
			mcplib.WithDescription("Consultar Contratos/Empenhos por Data de Atualização Global. Required: dataInicial, dataFinal. Optional: cnpjOrgao, codigoUnidadeAdministrativa, usuarioId. Returns array of RecuperarContratoDto."),
			mcplib.WithString("dataInicial", mcplib.Required(), mcplib.Description("Data inicial")),
			mcplib.WithString("dataFinal", mcplib.Required(), mcplib.Description("Data final")),
			mcplib.WithString("cnpjOrgao", mcplib.Description("Cnpj orgao")),
			mcplib.WithString("codigoUnidadeAdministrativa", mcplib.Description("Codigo unidade administrativa")),
			mcplib.WithString("usuarioId", mcplib.Description("Usuario id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/v1/contratos/atualizacao", []mcpParamBinding{{PublicName: "dataInicial", WireName: "dataInicial", Location: "query"}, {PublicName: "dataFinal", WireName: "dataFinal", Location: "query"}, {PublicName: "cnpjOrgao", WireName: "cnpjOrgao", Location: "query"}, {PublicName: "codigoUnidadeAdministrativa", WireName: "codigoUnidadeAdministrativa", Location: "query"}, {PublicName: "usuarioId", WireName: "usuarioId", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("contratos_consultar-por-data-publicacao",
			mcplib.WithDescription("Consultar Contratos por Data de Publicação. Required: dataInicial, dataFinal. Optional: cnpjOrgao, codigoUnidadeAdministrativa, usuarioId. Returns array of RecuperarContratoDto."),
			mcplib.WithString("dataInicial", mcplib.Required(), mcplib.Description("Data inicial")),
			mcplib.WithString("dataFinal", mcplib.Required(), mcplib.Description("Data final")),
			mcplib.WithString("cnpjOrgao", mcplib.Description("Cnpj orgao")),
			mcplib.WithString("codigoUnidadeAdministrativa", mcplib.Description("Codigo unidade administrativa")),
			mcplib.WithString("usuarioId", mcplib.Description("Usuario id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/v1/contratos", []mcpParamBinding{{PublicName: "dataInicial", WireName: "dataInicial", Location: "query"}, {PublicName: "dataFinal", WireName: "dataFinal", Location: "query"}, {PublicName: "cnpjOrgao", WireName: "cnpjOrgao", Location: "query"}, {PublicName: "codigoUnidadeAdministrativa", WireName: "codigoUnidadeAdministrativa", Location: "query"}, {PublicName: "usuarioId", WireName: "usuarioId", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("instrumentoscobranca_consultar-instrumentos",
			mcplib.WithDescription("Consultar Instrumentos de Cobrança por Data de Inclusão. Required: dataInicial, dataFinal. Optional: tipoInstrumentoCobranca, cnpjOrgao. Returns array of ConsultarInstrumentoCobrancaDto."),
			mcplib.WithString("dataInicial", mcplib.Required(), mcplib.Description("Data inicial")),
			mcplib.WithString("dataFinal", mcplib.Required(), mcplib.Description("Data final")),
			mcplib.WithString("tipoInstrumentoCobranca", mcplib.Description("Tipo instrumento cobranca")),
			mcplib.WithString("cnpjOrgao", mcplib.Description("Cnpj orgao")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/v1/instrumentoscobranca/inclusao", []mcpParamBinding{{PublicName: "dataInicial", WireName: "dataInicial", Location: "query"}, {PublicName: "dataFinal", WireName: "dataFinal", Location: "query"}, {PublicName: "tipoInstrumentoCobranca", WireName: "tipoInstrumentoCobranca", Location: "query"}, {PublicName: "cnpjOrgao", WireName: "cnpjOrgao", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("orgaos_compras_consultar",
			mcplib.WithDescription("Consultar Contratação. Required: cnpj, ano, sequencial. Returns the RecuperarCompraDto."),
			mcplib.WithString("cnpj", mcplib.Required(), mcplib.Description("Cnpj")),
			mcplib.WithString("ano", mcplib.Required(), mcplib.Description("Ano")),
			mcplib.WithString("sequencial", mcplib.Required(), mcplib.Description("Sequencial")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/v1/orgaos/{cnpj}/compras/{ano}/{sequencial}", []mcpParamBinding{{PublicName: "cnpj", WireName: "cnpj", Location: "path"}, {PublicName: "ano", WireName: "ano", Location: "path"}, {PublicName: "sequencial", WireName: "sequencial", Location: "path"}}, []string{"cnpj", "ano", "sequencial"}),
	)
	s.AddTool(
		mcplib.NewTool("pca_consultar-itens-por-ano",
			mcplib.WithDescription("Consultar Itens de PCA por Ano do PCA e Código de Classificação Superior. Required: anoPca, codigoClassificacaoSuperior. Returns array of PlanoContratacaoComItensDoUsuarioDto."),
			mcplib.WithString("anoPca", mcplib.Required(), mcplib.Description("Ano pca")),
			mcplib.WithString("codigoClassificacaoSuperior", mcplib.Required(), mcplib.Description("Codigo classificacao superior")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/v1/pca/", []mcpParamBinding{{PublicName: "anoPca", WireName: "anoPca", Location: "query"}, {PublicName: "codigoClassificacaoSuperior", WireName: "codigoClassificacaoSuperior", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("pca_consultar-itens-por-usuario-ano",
			mcplib.WithDescription("Consultar Itens de PCA por Ano do PCA, IdUsuario e Código de Classificação Superior. Required: anoPca, idUsuario. Optional: codigoClassificacaoSuperior, cnpj. Returns array of PlanoContratacaoComItensDoUsuarioDto."),
			mcplib.WithString("anoPca", mcplib.Required(), mcplib.Description("Ano pca")),
			mcplib.WithString("idUsuario", mcplib.Required(), mcplib.Description("Id usuario")),
			mcplib.WithString("codigoClassificacaoSuperior", mcplib.Description("Codigo classificacao superior")),
			mcplib.WithString("cnpj", mcplib.Description("Cnpj")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/v1/pca/usuario", []mcpParamBinding{{PublicName: "anoPca", WireName: "anoPca", Location: "query"}, {PublicName: "idUsuario", WireName: "idUsuario", Location: "query"}, {PublicName: "codigoClassificacaoSuperior", WireName: "codigoClassificacaoSuperior", Location: "query"}, {PublicName: "cnpj", WireName: "cnpj", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("pca_consultar-itens-por-usuario-ano-1",
			mcplib.WithDescription("Consultar PCA por Data de Atualização Global. Required: dataInicio, dataFim. Optional: cnpj, codigoUnidade. Returns array of PlanoContratacaoComItensDoUsuarioDto."),
			mcplib.WithString("dataInicio", mcplib.Required(), mcplib.Description("Data inicio")),
			mcplib.WithString("dataFim", mcplib.Required(), mcplib.Description("Data fim")),
			mcplib.WithString("cnpj", mcplib.Description("Cnpj")),
			mcplib.WithString("codigoUnidade", mcplib.Description("Codigo unidade")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/v1/pca/atualizacao", []mcpParamBinding{{PublicName: "dataInicio", WireName: "dataInicio", Location: "query"}, {PublicName: "dataFim", WireName: "dataFim", Location: "query"}, {PublicName: "cnpj", WireName: "cnpj", Location: "query"}, {PublicName: "codigoUnidade", WireName: "codigoUnidade", Location: "query"}}, []string{}),
	)
	// Search tool — faster than iterating list endpoints for finding specific items
	s.AddTool(
		mcplib.NewTool("search",
			mcplib.WithDescription("Full-text search across all synced data. Faster than paginating list endpoints. Requires sync first."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("Search query (supports FTS5 syntax: AND, OR, NOT, quotes for phrases)")),
			mcplib.WithNumber("limit", mcplib.Description("Max results (default 25)")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleSearch,
	)
	// SQL tool — ad-hoc analysis on synced data without API calls
	s.AddTool(
		mcplib.NewTool("sql",
			mcplib.WithDescription("Run read-only SQL against local database. Use for ad-hoc analysis, aggregations, and joins across synced resources. Requires sync first."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("SQL query (SELECT or WITH...SELECT). Tables match resource names.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleSQL,
	)

	// Context tool — front-loaded domain knowledge for agents.
	// Call this first to understand the API taxonomy, query patterns, and capabilities.
	s.AddTool(
		mcplib.NewTool("context",
			mcplib.WithDescription("Get API domain context: resource taxonomy, auth requirements, query tips, and unique capabilities. Call this first."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleContext,
	)

	// Runtime Cobra-tree mirror — exposes every user-facing command that is
	// not already covered by a typed endpoint or framework MCP tool.
	cobratree.RegisterAll(s, cli.RootCmd(), cobratree.SiblingCLIPath)
}

type mcpParamBinding struct {
	PublicName string
	WireName   string
	Location   string
}

// makeAPIHandler creates a generic MCP tool handler for an API endpoint.
func makeAPIHandler(method, pathTemplate string, bindings []mcpParamBinding, positionalParams []string) server.ToolHandlerFunc {
	return func(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
		c, err := newMCPClient()
		if err != nil {
			return mcplib.NewToolResultError(err.Error()), nil
		}

		// mcp-go v0.47+ made CallToolParams.Arguments an `any` to support
		// non-map payloads; GetArguments() returns the map[string]any shape
		// we rely on here (or an empty map when the payload is something else).
		args := req.GetArguments()

		// positionalParams mixes real URL path params with CLI positional
		// args that map to query params (e.g. `search <query>` -> ?query=);
		// the placeholder check below disambiguates them at runtime.
		path := pathTemplate
		knownArgs := make(map[string]bool, len(bindings))
		pathParams := make(map[string]bool, len(positionalParams))
		params := make(map[string]string)
		bodyArgs := make(map[string]any)
		for _, binding := range bindings {
			knownArgs[binding.PublicName] = true
			v, ok := args[binding.PublicName]
			if !ok {
				continue
			}
			switch binding.Location {
			case "path":
				placeholder := "{" + binding.WireName + "}"
				pathParams[binding.PublicName] = true
				path = strings.Replace(path, placeholder, fmt.Sprintf("%v", v), 1)
			case "body":
				bodyArgs[binding.WireName] = v
			default:
				params[binding.WireName] = fmt.Sprintf("%v", v)
			}
		}
		for _, p := range positionalParams {
			placeholder := "{" + p + "}"
			if !strings.Contains(pathTemplate, placeholder) {
				continue
			}
			pathParams[p] = true
			if v, ok := args[p]; ok {
				path = strings.Replace(path, placeholder, fmt.Sprintf("%v", v), 1)
			}
		}

		for k, v := range args {
			if pathParams[k] || knownArgs[k] {
				continue
			}
			switch method {
			case "POST", "PUT", "PATCH":
				bodyArgs[k] = v
			default:
				params[k] = fmt.Sprintf("%v", v)
			}
		}

		var data json.RawMessage
		switch method {
		case "GET":
			data, err = c.Get(path, params)
		case "POST":
			body, _ := json.Marshal(bodyArgs)
			data, _, err = c.Post(path, body)
		case "PUT":
			body, _ := json.Marshal(bodyArgs)
			data, _, err = c.Put(path, body)
		case "PATCH":
			body, _ := json.Marshal(bodyArgs)
			data, _, err = c.Patch(path, body)
		case "DELETE":
			data, _, err = c.Delete(path)
		default:
			return mcplib.NewToolResultError("unsupported method: " + method), nil
		}

		if err != nil {
			msg := err.Error()
			switch {
			case strings.Contains(msg, "HTTP 409"):
				return mcplib.NewToolResultText("already exists (no-op)"), nil
			case strings.Contains(msg, "HTTP 400") && cliutil.LooksLikeAuthError(msg):
				return mcplib.NewToolResultError("authentication error: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: the API rejected the request — this usually means auth is missing or invalid." +
					"\n      Set your API key: export PNCP_CONSULTA_BEARER_AUTH=<your-key>" +
					"\n      See API docs: https://www.serpro.gov.br" +
					"\n      Run 'pncp-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 401"):
				return mcplib.NewToolResultError("authentication failed: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: check your token." +
					"\n      Set it with: export PNCP_CONSULTA_BEARER_AUTH=<your-key>" +
					"\n      See API docs: https://www.serpro.gov.br" +
					"\n      Run 'pncp-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 403"):
				return mcplib.NewToolResultError("permission denied: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: your credentials are valid but lack access to this resource." +
					"\n      Set it with: export PNCP_CONSULTA_BEARER_AUTH=<your-key>" +
					"\n      See API docs: https://www.serpro.gov.br" +
					"\n      Run 'pncp-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 404"):
				if method == "DELETE" {
					return mcplib.NewToolResultText("already deleted (no-op)"), nil
				}
				return mcplib.NewToolResultError("not found: " + msg), nil
			case strings.Contains(msg, "HTTP 429"):
				return mcplib.NewToolResultError("rate limited: " + msg), nil
			default:
				return mcplib.NewToolResultError(msg), nil
			}
		}

		// For GET responses, wrap bare arrays with count metadata
		if method == "GET" {
			trimmed := strings.TrimSpace(string(data))
			if len(trimmed) > 0 && trimmed[0] == '[' {
				var items []json.RawMessage
				if json.Unmarshal(data, &items) == nil {
					wrapped := map[string]any{
						"count": len(items),
						"items": items,
					}
					out, _ := json.Marshal(wrapped)
					return mcplib.NewToolResultText(string(out)), nil
				}
			}
		}
		return mcplib.NewToolResultText(string(data)), nil
	}
}

func newMCPClient() (*client.Client, error) {
	home, _ := os.UserHomeDir()
	cfgPath := filepath.Join(home, ".config", "pncp-pp-cli", "config.toml")
	cfg, err := config.Load(cfgPath)
	if err != nil {
		return nil, fmt.Errorf("loading config: %w", err)
	}
	c := client.New(cfg, 30*time.Second, 0)
	// Agents calling through MCP need fresh data every call. The on-disk
	// response cache survives across MCP server invocations, so a
	// DELETE/PATCH followed by a GET would otherwise return the
	// pre-mutation snapshot for up to the cache TTL. The interactive CLI
	// constructs its own client and is unaffected.
	c.NoCache = true
	return c, nil
}

func dbPath() string {
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".local", "share", "pncp-pp-cli", "data.db")
}

// Note: MCP tools use their own dbPath() because they are in a separate package (main, not cli).
// The CLI's defaultDBPath() in the cli package uses the same canonical path.

func handleSearch(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	query, ok := args["query"].(string)
	if !ok || query == "" {
		return mcplib.NewToolResultError("query is required"), nil
	}

	limit := 25
	if v, ok := args["limit"].(float64); ok && v > 0 {
		limit = int(v)
	}

	db, err := store.OpenReadOnly(dbPath())
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("opening database: %v", err)), nil
	}
	defer db.Close()

	results, err := db.Search(query, limit)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("search failed: %v", err)), nil
	}

	data, _ := json.MarshalIndent(results, "", "  ")
	return mcplib.NewToolResultText(string(data)), nil
}

// validateReadOnlyQuery gates the MCP sql tool. The agent contract advertised
// to the host is ReadOnlyHintAnnotation(true); a false annotation on a
// mutating tool lets MCP hosts auto-approve writes and is treated as a real
// bug per the project's agent-native security model.
//
// The gate is an allowlist (SELECT or WITH only) applied AFTER stripping the
// leading whitespace, line comments, block comments, and semicolons that
// SQLite itself ignores before parsing. A naive HasPrefix check on a
// keyword blocklist is bypassable by prefixing the dangerous statement with
// "/* x */" or "-- x\n" — TrimSpace strips outer whitespace but does not
// understand SQL comment syntax. Combined with the empirical fact that
// modernc.org/sqlite's mode=ro does NOT block VACUUM INTO (writes a snapshot
// to a new file) or ATTACH DATABASE (opens a separate writable handle),
// such a bypass produces silent exfiltration to an attacker-chosen path.
//
// SELECT and WITH are the only allowed leading keywords. WITH supports
// SELECT-form CTEs; CTE-wrapped writes ("WITH x AS (...) INSERT ...") are
// caught by OpenReadOnly's mode=ro one layer down. PRAGMA, ATTACH, VACUUM,
// and every other DDL/DML keyword fail at this gate before reaching SQLite.
func validateReadOnlyQuery(query string) error {
	upper := strings.ToUpper(stripLeadingSQLNoise(query))
	if !strings.HasPrefix(upper, "SELECT") && !strings.HasPrefix(upper, "WITH") {
		return fmt.Errorf("only SELECT queries are allowed")
	}
	return nil
}

// stripLeadingSQLNoise removes leading whitespace, SQL line comments
// (-- to end of line), block comments (/* ... */), and statement
// separators (;) from query. SQLite skips these before parsing the first
// keyword, so a security gate that does not strip them mismatches what the
// driver actually executes.
func stripLeadingSQLNoise(query string) string {
	for {
		query = strings.TrimLeft(query, " \t\r\n;")
		switch {
		case strings.HasPrefix(query, "--"):
			if idx := strings.IndexByte(query, '\n'); idx >= 0 {
				query = query[idx+1:]
				continue
			}
			return ""
		case strings.HasPrefix(query, "/*"):
			if idx := strings.Index(query[2:], "*/"); idx >= 0 {
				query = query[2+idx+2:]
				continue
			}
			return ""
		default:
			return query
		}
	}
}

func handleSQL(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	query, ok := args["query"].(string)
	if !ok || query == "" {
		return mcplib.NewToolResultError("query is required"), nil
	}

	if err := validateReadOnlyQuery(query); err != nil {
		return mcplib.NewToolResultError(err.Error()), nil
	}

	db, err := store.OpenReadOnly(dbPath())
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("opening database: %v", err)), nil
	}
	defer db.Close()

	rows, err := db.Query(query)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("query failed: %v", err)), nil
	}
	defer rows.Close()

	cols, _ := rows.Columns()
	var results []map[string]any
	for rows.Next() {
		values := make([]any, len(cols))
		ptrs := make([]any, len(cols))
		for i := range values {
			ptrs[i] = &values[i]
		}
		rows.Scan(ptrs...)
		row := make(map[string]any)
		for i, col := range cols {
			row[col] = values[i]
		}
		results = append(results, row)
	}

	data, _ := json.MarshalIndent(results, "", "  ")
	return mcplib.NewToolResultText(string(data)), nil
}

func handleContext(_ context.Context, _ mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	ctx := map[string]any{
		"api":         "pncp",
		"description": "API REST de serviços do Portal Nacional de Contratações Públicas (PNCP)",
		"archetype":   "generic",
		"tool_count":  12,
		// tool_surface tells agents which surface a capability lives on.
		"tool_surface": "MCP exposes typed endpoint tools plus a runtime mirror of user-facing CLI commands. Endpoint tools keep typed schemas; command-mirror tools shell out to the companion pncp-pp-cli binary.",
		"auth": map[string]any{
			"type": "bearer_token",
			"env_vars": []map[string]any{
				{
					"name":        "PNCP_CONSULTA_BEARER_AUTH",
					"kind":        "per_call",
					"required":    true,
					"sensitive":   true,
					"description": "Set to your API credential.",
				},
			},
			"docs_url": "https://www.serpro.gov.br",
		},
		"resources": []map[string]any{
			{
				"name":        "atas",
				"description": "Consultas de Atas de Registro de Preços",
				"endpoints":   []string{"consultar-registro-preco-data-atualizacao", "consultar-registro-preco-periodo"},
				"searchable":  true,
			},
			{
				"name":        "contratacoes",
				"description": "Manage contratacoes",
				"endpoints":   []string{"consultar-contratacao-periodo-recebimento-propostas", "consultar-contratacao-por-data-de-publicacao", "consultar-contratacao-por-data-ultima-atualizacao"},
				"searchable":  true,
			},
			{
				"name":        "contratos",
				"description": "Manage contratos",
				"endpoints":   []string{"consultar-por-data-atualizacao-global", "consultar-por-data-publicacao"},
				"searchable":  true,
			},
			{
				"name":        "instrumentoscobranca",
				"description": "Manage instrumentoscobranca",
				"endpoints":   []string{"consultar-instrumentos"},
				"searchable":  true,
			},
			{
				"name":        "orgaos",
				"description": "Manage orgaos",
				"endpoints":   []string{},
			},
			{
				"name":        "pca",
				"description": "Manage pca",
				"endpoints":   []string{"consultar-itens-por-ano", "consultar-itens-por-usuario-ano", "consultar-itens-por-usuario-ano-1"},
				"searchable":  true,
			},
		},
		"query_tips": []string{
			"Pagination uses cursor-based paging. Pass after parameter for subsequent pages.",
			"Control page size with the limit parameter (default 100).",
			"Use the sql tool for ad-hoc analysis on synced data. Run sync first to populate the local database.",
			"Use the search tool for full-text search across all synced resources. Faster than iterating list endpoints.",
			"Prefer sql/search over repeated API calls when the data is already synced.",
		},
	}
	data, _ := json.MarshalIndent(ctx, "", "  ")
	return mcplib.NewToolResultText(string(data)), nil
}

// RegisterNovelFeatureTools is kept as a compatibility no-op for older MCP
// mains. New generated mains call RegisterTools only; RegisterTools now
// includes the runtime Cobra-tree mirror.
func RegisterNovelFeatureTools(s *server.MCPServer) {
	_ = s
}
