# BALIZA Unified Endpoint Configuration
# Single source of truth for PNCP API endpoints used by both dbt and Python
# ADR-009: dbt-Driven Task Planning Architecture

version: "1.0"
api_base_url: "https://pncp.gov.br/api/consulta"
default_settings:
  request_timeout: 30
  user_agent: "BALIZA/3.0 (Backup Aberto de Licitacoes)"
  max_days: 365
  concurrency: 8
  rate_limit_delay: 0.0

endpoints:
  contratos_publicacao:
    path: "/v1/contratos"
    description: "Contratos por Data de Publicação"
    date_params: ["dataInicial", "dataFinal"]
    supports_date_range: true
    page_size: 500
    granularity: "month"  # dbt planning granularity
    modalidades: []  # No modalidade iteration needed
    active: true
    
  contratos_atualizacao:
    path: "/v1/contratos/atualizacao"
    description: "Contratos por Data de Atualização Global"
    date_params: ["dataInicial", "dataFinal"]
    supports_date_range: true
    page_size: 500
    granularity: "month"
    modalidades: []
    active: true
    
  atas_periodo:
    path: "/v1/atas"
    description: "Atas de Registro de Preço por Período de Vigência"
    date_params: ["dataInicial", "dataFinal"]
    supports_date_range: true
    page_size: 500
    granularity: "month"
    modalidades: []
    active: true
    
  atas_atualizacao:
    path: "/v1/atas/atualizacao"
    description: "Atas por Data de Atualização Global"
    date_params: ["dataInicial", "dataFinal"]
    supports_date_range: true
    page_size: 500
    granularity: "month"
    modalidades: []
    active: true
    
  contratacoes_publicacao:
    path: "/v1/contratacoes/publicacao"
    description: "Contratações por Data de Publicação"
    date_params: ["dataInicial", "dataFinal"]
    supports_date_range: true
    page_size: 50
    granularity: "month"
    modalidades: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 99]  # ModalidadeContratacao values
    active: true
    
  contratacoes_atualizacao:
    path: "/v1/contratacoes/atualizacao"
    description: "Contratações por Data de Atualização Global"
    date_params: ["dataInicial", "dataFinal"]
    supports_date_range: true
    page_size: 50
    granularity: "month"
    modalidades: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 99]
    active: true
    
  pca_atualizacao:
    path: "/v1/pca/atualizacao"
    description: "PCA por Data de Atualização Global"
    date_params: ["dataInicio", "dataFim"]  # Different parameter names
    supports_date_range: true
    page_size: 500
    granularity: "month"
    modalidades: []
    active: true
    
  instrumentoscobranca_inclusao:
    path: "/v1/instrumentoscobranca/inclusao"
    description: "Instrumentos de Cobrança por Data de Inclusão"
    date_params: ["dataInicial", "dataFinal"]
    supports_date_range: true
    page_size: 100
    min_page_size: 10
    granularity: "month"
    modalidades: []
    active: true
    
  contratacoes_proposta:
    path: "/v1/contratacoes/proposta"
    description: "Contratações com Recebimento de Propostas Aberto"
    date_params: ["dataFinal"]
    supports_date_range: false
    requires_single_date: true
    requires_future_date: true
    future_days_offset: 1825  # 5 years
    page_size: 50
    granularity: "month"
    modalidades: []
    active: true

# Environment-specific overrides
environments:
  dev:
    concurrency: 4
    page_size_override: {}
  staging:
    concurrency: 6
    page_size_override: {}
  prod:
    concurrency: 8
    page_size_override: {}

# Metadata for fingerprinting
fingerprint_excludes:
  - "environments"
  - "default_settings.user_agent"
  # Exclude secrets and environment-specific configs from fingerprint