from kedro.pipeline import Pipeline, node
from .seeds_nodes import load_seed

def create_pipeline(**kwargs):
    return Pipeline(
        [
            node(
                func=load_seed,
                inputs="benefit_type_seed",
                outputs="benefit_type",
                name="load_benefit_type_seed",
            ),
            node(
                func=load_seed,
                inputs="bidding_mode_seed",
                outputs="bidding_mode",
                name="load_bidding_mode_seed",
            ),
            node(
                func=load_seed,
                inputs="call_instrument_seed",
                outputs="call_instrument",
                name="load_call_instrument_seed",
            ),
            node(
                func=load_seed,
                inputs="contract_term_type_seed",
                outputs="contract_term_type",
                name="load_contract_term_type_seed",
            ),
            node(
                func=load_seed,
                inputs="contract_type_seed",
                outputs="contract_type",
                name="load_contract_type_seed",
            ),
            node(
                func=load_seed,
                inputs="item_situation_seed",
                outputs="item_situation",
                name="load_item_situation_seed",
            ),
            node(
                func=load_seed,
                inputs="judgment_criteria_seed",
                outputs="judgment_criteria",
                name="load_judgment_criteria_seed",
            ),
            node(
                func=load_seed,
                inputs="modalidade_contratacao_seed",
                outputs="modalidade_contratacao",
                name="load_modalidade_contratacao_seed",
            ),
            node(
                func=load_seed,
                inputs="natureza_juridica_seed",
                outputs="natureza_juridica",
                name="load_natureza_juridica_seed",
            ),
            node(
                func=load_seed,
                inputs="process_category_seed",
                outputs="process_category",
                name="load_process_category_seed",
            ),
            node(
                func=load_seed,
                inputs="result_situation_seed",
                outputs="result_situation",
                name="load_result_situation_seed",
            ),
            node(
                func=load_seed,
                inputs="situacao_contratacao_seed",
                outputs="situacao_contratacao",
                name="load_situacao_contratacao_seed",
            ),
            node(
                func=load_seed,
                inputs="uf_brasil_seed",
                outputs="uf_brasil",
                name="load_uf_brasil_seed",
            ),
            node(
                func=load_seed,
                inputs="endpoints_config_seed",
                outputs="endpoints_config",
                name="load_endpoints_config_seed",
            ),
            node(
                func=load_seed,
                inputs="modalidades_config_seed",
                outputs="modalidades_config",
                name="load_modalidades_config_seed",
            ),
        ]
    )
