#!/usr/bin/env -S uv run --quiet
"""Builds frontend configuration by exposing PNCPResource frontend mappings.

Reads from the live ``baliza.resources.RESOURCES`` registry so adding a
new resource is a single-file change: registering it in the registry and
declaring its ``frontend_exposures`` automatically surfaces it to the
web app on the next build. The legacy ``baliza.pncp_resources`` module
was killed in Drift-0.
"""
from __future__ import annotations

import sys
from pathlib import Path

# Adjust path if script is run outside the root.
REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "src"))

from baliza.resources import RESOURCES  # noqa: E402


def main() -> int:
    out_dir = REPO_ROOT / "web" / "src" / "lib" / "generated"
    out_dir.mkdir(parents=True, exist_ok=True)
    out_file = out_dir / "frontend_exposures.ts"

    lines = []
    lines.append("// This file is auto-generated by scripts/build_frontend_config.py")
    lines.append("// Do not edit manually.")
    lines.append("")
    lines.append("export const FRONTEND_EXPOSURES = [")

    for resource in RESOURCES.values():
        for exposure in resource.frontend_exposures:
            lines.append("  {")
            lines.append(f"    artifact_name: '{exposure.artifact_name}',")
            lines.append(f"    table_alias: '{exposure.table_alias}',")
            lines.append(f"    is_canonical: {'true' if exposure.is_canonical else 'false'}")
            lines.append("  },")

    lines.append("] as const;")
    lines.append("")

    out_file.write_text("\n".join(lines))
    print(f"Generated {out_file.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
