version: 2

sources:
  - name: pncp_api
    description: "Direct access to PNCP API endpoints"
    loader: httpfs
    tables:
      - name: contratos_publicacao
        description: "Contratos por Data de Publicação"
        config:
          external_location: "{{ get_pncp_api_url('contratos_publicacao') }}"
      - name: contratos_atualizacao
        description: "Contratos por Data de Atualização Global"
        config:
          external_location: "{{ get_pncp_api_url('contratos_atualizacao') }}"
      - name: atas_periodo
        description: "Atas de Registro de Preço por Período de Vigência"
        config:
          external_location: "{{ get_pncp_api_url('atas_periodo') }}"
      - name: atas_atualizacao
        description: "Atas por Data de Atualização Global"
        config:
          external_location: "{{ get_pncp_api_url('atas_atualizacao') }}"
      - name: contratacoes_publicacao
        description: "Contratações por Data de Publicação"
        config:
          external_location: "{{ get_pncp_api_url('contratacoes_publicacao') }}"
      - name: contratacoes_atualizacao
        description: "Contratações por Data de Atualização"
        config:
          external_location: "{{ get_pncp_api_url('contratacoes_atualizacao') }}"
      - name: contratacoes_proposta
        description: "Contratações com Recebimento de Propostas Aberto"
        config:
          external_location: "{{ get_pncp_api_url('contratacoes_proposta') }}"

  - name: psa
    description: "Persistent Staging Area - Raw PNCP API responses (Legacy)"
    schema: psa
    tables:
      - name: pncp_raw_responses
        description: "All raw PNCP API responses with complete metadata"