version: 2

models:
  - name: silver_pncp_contratacoes
    description: "Cleaned and validated PNCP contratacoes data"
    columns:
      - name: numeroControlePNCP
        tests:
          - unique
          - not_null
      - name: anoContratacao
        tests:
          - not_null
      - name: cnpjOrgao
        tests:
          - not_null
      - name: modalidadeId
        tests:
          - not_null
          - test_enum_drift:
              seed_name: 'modalidade_contratacao'
  - name: silver_pncp_orgaos_entidades
    description: "Cleaned and validated PNCP orgaos e entidades data"
    columns:
      - name: sequencialOrgao
        tests:
          - unique
          - not_null
      - name: cnpjOrgao
        tests:
          - test_cnpj_format
  - name: silver_pncp_contratos
    description: "Cleaned and validated PNCP contratos data"
    columns:
      - name: numeroControlePNCPContrato
        tests:
          - unique
          - not_null
      - name: numeroControlePNCP
        tests:
          - relationships:
              to: ref('silver_pncp_contratacoes')
              field: numeroControlePNCP
