// Copyright 2026 claude. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newAtasCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "atas",
		Short:  "Consultas de Atas de Registro de Preços",
		Hidden: true,
	}

	cmd.AddCommand(newAtasConsultarRegistroPrecoDataAtualizacaoCmd(flags))
	cmd.AddCommand(newAtasConsultarRegistroPrecoPeriodoCmd(flags))
	return cmd
}
