// Copyright 2026 claude. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newContratosConsultarPorDataPublicacaoCmd(flags *rootFlags) *cobra.Command {
	var flagDataInicial string
	var flagDataFinal string
	var flagCnpjOrgao string
	var flagCodigoUnidadeAdministrativa string
	var flagUsuarioId string

	cmd := &cobra.Command{
		Use:         "consultar-por-data-publicacao",
		Short:       "Consultar Contratos por Data de Publicação",
		Example:     "  pncp-pp-cli contratos consultar-por-data-publicacao --data-inicial example-value --data-final example-value",
		Annotations: map[string]string{"pp:endpoint": "contratos.consultar-por-data-publicacao", "pp:method": "GET", "pp:path": "/v1/contratos", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if !cmd.Flags().Changed("data-inicial") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "data-inicial")
			}
			if !cmd.Flags().Changed("data-final") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "data-final")
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/v1/contratos"
			params := map[string]string{}
			if flagDataInicial != "" {
				params["dataInicial"] = fmt.Sprintf("%v", flagDataInicial)
			}
			if flagDataFinal != "" {
				params["dataFinal"] = fmt.Sprintf("%v", flagDataFinal)
			}
			if flagCnpjOrgao != "" {
				params["cnpjOrgao"] = fmt.Sprintf("%v", flagCnpjOrgao)
			}
			if flagCodigoUnidadeAdministrativa != "" {
				params["codigoUnidadeAdministrativa"] = fmt.Sprintf("%v", flagCodigoUnidadeAdministrativa)
			}
			if flagUsuarioId != "" {
				params["usuarioId"] = fmt.Sprintf("%v", flagUsuarioId)
			}
			data, prov, err := resolveRead(cmd.Context(), c, flags, "contratos", false, path, params, nil)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output
			{
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagDataInicial, "data-inicial", "", "Data inicial")
	cmd.Flags().StringVar(&flagDataFinal, "data-final", "", "Data final")
	cmd.Flags().StringVar(&flagCnpjOrgao, "cnpj-orgao", "", "Cnpj orgao")
	cmd.Flags().StringVar(&flagCodigoUnidadeAdministrativa, "codigo-unidade-administrativa", "", "Codigo unidade administrativa")
	cmd.Flags().StringVar(&flagUsuarioId, "usuario-id", "", "Usuario id")

	return cmd
}
