// Copyright 2026 claude. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newContratacoesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "contratacoes",
		Short:  "Manage contratacoes",
		Hidden: true,
	}

	cmd.AddCommand(newContratacoesConsultarContratacaoPeriodoRecebimentoPropostasCmd(flags))
	cmd.AddCommand(newContratacoesConsultarContratacaoPorDataDePublicacaoCmd(flags))
	cmd.AddCommand(newContratacoesConsultarContratacaoPorDataUltimaAtualizacaoCmd(flags))
	return cmd
}
