// Copyright 2026 claude. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newContratosCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "contratos",
		Short:  "Manage contratos",
		Hidden: true,
	}

	cmd.AddCommand(newContratosConsultarPorDataAtualizacaoGlobalCmd(flags))
	cmd.AddCommand(newContratosConsultarPorDataPublicacaoCmd(flags))
	return cmd
}
