// Copyright 2026 claude. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newPcaCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "pca",
		Short:  "Manage pca",
		Hidden: true,
	}

	cmd.AddCommand(newPcaConsultarItensPorAnoCmd(flags))
	cmd.AddCommand(newPcaConsultarItensPorUsuarioAnoCmd(flags))
	cmd.AddCommand(newPcaConsultarItensPorUsuarioAno1Cmd(flags))
	return cmd
}
