// Copyright 2026 claude. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newPcaConsultarItensPorUsuarioAno1Cmd(flags *rootFlags) *cobra.Command {
	var flagDataInicio string
	var flagDataFim string
	var flagCnpj string
	var flagCodigoUnidade string

	cmd := &cobra.Command{
		Use:         "consultar-itens-por-usuario-ano-1",
		Short:       "Consultar PCA por Data de Atualização Global",
		Example:     "  pncp-pp-cli pca consultar-itens-por-usuario-ano-1 --data-inicio example-value --data-fim example-value",
		Annotations: map[string]string{"pp:endpoint": "pca.consultar-itens-por-usuario-ano-1", "pp:method": "GET", "pp:path": "/v1/pca/atualizacao", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if !cmd.Flags().Changed("data-inicio") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "data-inicio")
			}
			if !cmd.Flags().Changed("data-fim") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "data-fim")
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/v1/pca/atualizacao"
			params := map[string]string{}
			if flagDataInicio != "" {
				params["dataInicio"] = fmt.Sprintf("%v", flagDataInicio)
			}
			if flagDataFim != "" {
				params["dataFim"] = fmt.Sprintf("%v", flagDataFim)
			}
			if flagCnpj != "" {
				params["cnpj"] = fmt.Sprintf("%v", flagCnpj)
			}
			if flagCodigoUnidade != "" {
				params["codigoUnidade"] = fmt.Sprintf("%v", flagCodigoUnidade)
			}
			data, prov, err := resolveRead(cmd.Context(), c, flags, "pca", false, path, params, nil)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output
			{
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagDataInicio, "data-inicio", "", "Data inicio")
	cmd.Flags().StringVar(&flagDataFim, "data-fim", "", "Data fim")
	cmd.Flags().StringVar(&flagCnpj, "cnpj", "", "Cnpj")
	cmd.Flags().StringVar(&flagCodigoUnidade, "codigo-unidade", "", "Codigo unidade")

	return cmd
}
