// Copyright 2026 claude. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newPcaConsultarItensPorUsuarioAnoCmd(flags *rootFlags) *cobra.Command {
	var flagAnoPca int
	var flagIdUsuario int
	var flagCodigoClassificacaoSuperior string
	var flagCnpj string

	cmd := &cobra.Command{
		Use:         "consultar-itens-por-usuario-ano",
		Short:       "Consultar Itens de PCA por Ano do PCA, IdUsuario e Código de Classificação Superior",
		Example:     "  pncp-pp-cli pca consultar-itens-por-usuario-ano --ano-pca 42 --id-usuario 42",
		Annotations: map[string]string{"pp:endpoint": "pca.consultar-itens-por-usuario-ano", "pp:method": "GET", "pp:path": "/v1/pca/usuario", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if !cmd.Flags().Changed("ano-pca") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "ano-pca")
			}
			if !cmd.Flags().Changed("id-usuario") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "id-usuario")
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/v1/pca/usuario"
			params := map[string]string{}
			if flagAnoPca != 0 {
				params["anoPca"] = fmt.Sprintf("%v", flagAnoPca)
			}
			if flagIdUsuario != 0 {
				params["idUsuario"] = fmt.Sprintf("%v", flagIdUsuario)
			}
			if flagCodigoClassificacaoSuperior != "" {
				params["codigoClassificacaoSuperior"] = fmt.Sprintf("%v", flagCodigoClassificacaoSuperior)
			}
			if flagCnpj != "" {
				params["cnpj"] = fmt.Sprintf("%v", flagCnpj)
			}
			data, prov, err := resolveRead(cmd.Context(), c, flags, "pca", false, path, params, nil)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output
			{
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().IntVar(&flagAnoPca, "ano-pca", 0, "Ano pca")
	cmd.Flags().IntVar(&flagIdUsuario, "id-usuario", 0, "Id usuario")
	cmd.Flags().StringVar(&flagCodigoClassificacaoSuperior, "codigo-classificacao-superior", "", "Codigo classificacao superior")
	cmd.Flags().StringVar(&flagCnpj, "cnpj", "", "Cnpj")

	return cmd
}
