# generated by datamodel-codegen:
#   filename:  api-pncp-consulta.json
#   timestamp: 2026-04-15T14:28:22+00:00

from __future__ import annotations

from datetime import date
from datetime import datetime as AwareDatetime
from enum import IntEnum, StrEnum

from pydantic import BaseModel, ConfigDict, Field


class RespostaErroValidacaoDTO(BaseModel):
    message: str | None = None
    path: str | None = None
    timestamp: str | None = None
    status: str | None = None
    error: str | None = None


class PlanoContratacaoItemDTO(BaseModel):
    nomeClassificacaoCatalogo: str | None = None
    quantidadeEstimada: float | None = None
    descricaoItem: str | None = None
    pdmCodigo: str | None = None
    dataInclusao: AwareDatetime | None = Field(None, examples=["2025-07-11T13:08:48"])
    numeroItem: int | None = None
    dataAtualizacao: AwareDatetime | None = Field(None, examples=["2025-07-11T13:08:48"])
    valorTotal: float | None = None
    pdmDescricao: str | None = None
    codigoItem: str | None = None
    unidadeRequisitante: str | None = None
    grupoContratacaoCodigo: str | None = None
    grupoContratacaoNome: str | None = None
    classificacaoSuperiorCodigo: str | None = None
    classificacaoSuperiorNome: str | None = None
    unidadeFornecimento: str | None = None
    valorUnitario: float | None = None
    valorOrcamentoExercicio: float | None = None
    dataDesejada: date | None = None
    classificacaoCatalogoId: int | None = None
    categoriaItemPcaNome: str | None = None


class ContratacaoFonteOrcamentariaDTO(BaseModel):
    codigo: int | None = None
    nome: str | None = None
    descricao: str | None = None
    dataInclusao: AwareDatetime | None = Field(None, examples=["2025-07-11T13:08:48"])


class RecuperarAmparoLegalDTO(BaseModel):
    descricao: str | None = None
    nome: str | None = None
    codigo: int | None = None


class IndicadorOrcamentoSigiloso(StrEnum):
    COMPRA_SEM_SIGILO = "COMPRA_SEM_SIGILO"
    COMPRA_PARCIALMENTE_SIGILOSA = "COMPRA_PARCIALMENTE_SIGILOSA"
    COMPRA_TOTALMENTE_SIGILOSA = "COMPRA_TOTALMENTE_SIGILOSA"


class SituacaoCompraId(IntEnum):
    # The PNCP OpenAPI spec declares these as strings, but the live
    # ``/v1/contratacoes/publicacao`` endpoint returns them as integers
    # (verified via scripts/probe_publicacoes.py — every record carried
    # ``situacaoCompraId: 1``, never ``"1"``). Treat them as ints so
    # RecuperarCompraPublicacaoDTO actually validates against real
    # payloads. The four-value range stays as published.
    field_1 = 1
    field_2 = 2
    field_3 = 3
    field_4 = 4


class RecuperarOrgaoEntidadeDTO(BaseModel):
    cnpj: str | None = None
    razaoSocial: str | None = None
    poderId: str | None = None
    esferaId: str | None = None


class RecuperarUnidadeOrgaoDTO(BaseModel):
    ufNome: str | None = None
    codigoUnidade: str | None = None
    nomeUnidade: str | None = None
    ufSigla: str | None = None
    municipioNome: str | None = None
    codigoIbge: str | None = None


class Categoria(BaseModel):
    id: int | None = None
    nome: str | None = None


class EventoNotaFiscalConsultaDTO(BaseModel):
    dataEvento: str | None = None
    tipoEvento: str | None = None
    evento: str | None = None
    motivoEvento: str | None = None


class ItemNotaFiscalConsultaDTO(BaseModel):
    numeroItem: str | None = None
    descricaoProdutoServico: str | None = None
    codigoNCM: str | None = None
    descricaoNCM: str | None = None
    cfop: str | None = None
    quantidade: str | None = None
    unidade: str | None = None
    valorUnitario: str | None = None
    valorTotal: str | None = None


class NotaFiscalEletronicaConsultaDTO(BaseModel):
    instrumentoCobrancaId: int | None = None
    chave: str | None = None
    nfTransparenciaID: int | None = None
    numero: int | None = None
    serie: int | None = None
    dataEmissao: str | None = None
    niEmitente: str | None = None
    nomeEmitente: str | None = None
    nomeMunicipioEmitente: str | None = None
    codigoOrgaoDestinatario: str | None = None
    nomeOrgaoDestinatario: str | None = None
    codigoOrgaoSuperiorDestinatario: str | None = None
    nomeOrgaoSuperiorDestinatario: str | None = None
    valorNotaFiscal: str | None = None
    tipoEventoMaisRecente: str | None = None
    dataTipoEventoMaisRecente: str | None = None
    dataInclusao: AwareDatetime | None = Field(None, examples=["2025-07-11T13:08:48"])
    dataAtualizacao: AwareDatetime | None = Field(None, examples=["2025-07-11T13:08:48"])
    itens: list[ItemNotaFiscalConsultaDTO] | None = None
    eventos: list[EventoNotaFiscalConsultaDTO] | None = None


class TipoPessoa(StrEnum):
    PJ = "PJ"
    PF = "PF"
    PE = "PE"


class TipoPessoaSubContratada(StrEnum):
    PJ = "PJ"
    PF = "PF"
    PE = "PE"


class TipoContrato(BaseModel):
    id: int | None = None
    nome: str | None = None


class TipoInstrumentoCobrancaDTO(BaseModel):
    id: int | None = None
    nome: str | None = None
    descricao: str | None = None
    dataInclusao: AwareDatetime | None = Field(None, examples=["2025-07-11T13:08:48"])
    dataAtualizacao: AwareDatetime | None = Field(None, examples=["2025-07-11T13:08:48"])
    statusAtivo: bool | None = None


class RecuperarCompraPublicacaoDTO(BaseModel):
    srp: bool | None = None
    orgaoEntidade: RecuperarOrgaoEntidadeDTO | None = None
    anoCompra: int | None = None
    sequencialCompra: int | None = None
    dataInclusao: AwareDatetime | None = Field(None, examples=["2025-07-11T13:08:48"])
    dataPublicacaoPncp: AwareDatetime | None = Field(None, examples=["2025-07-11T13:08:48"])
    dataAtualizacao: AwareDatetime | None = Field(None, examples=["2025-07-11T13:08:48"])
    numeroCompra: str | None = None
    unidadeOrgao: RecuperarUnidadeOrgaoDTO | None = None
    amparoLegal: RecuperarAmparoLegalDTO | None = None
    dataAberturaProposta: AwareDatetime | None = Field(None, examples=["2025-07-11T13:08:48"])
    dataEncerramentoProposta: AwareDatetime | None = Field(None, examples=["2025-07-11T13:08:48"])
    informacaoComplementar: str | None = None
    processo: str | None = None
    objetoCompra: str | None = None
    linkSistemaOrigem: str | None = None
    justificativaPresencial: str | None = None
    unidadeSubRogada: RecuperarUnidadeOrgaoDTO | None = None
    orgaoSubRogado: RecuperarOrgaoEntidadeDTO | None = None
    valorTotalHomologado: float | None = None
    linkProcessoEletronico: str | None = None
    numeroControlePNCP: str | None = None
    modalidadeId: int | None = None
    dataAtualizacaoGlobal: AwareDatetime | None = Field(None, examples=["2025-07-11T13:08:48"])
    modoDisputaId: int | None = None
    valorTotalEstimado: float | None = None
    modalidadeNome: str | None = None
    modoDisputaNome: str | None = None
    tipoInstrumentoConvocatorioCodigo: int | None = None
    tipoInstrumentoConvocatorioNome: str | None = None
    fontesOrcamentarias: list[ContratacaoFonteOrcamentariaDTO] | None = None
    situacaoCompraId: SituacaoCompraId | None = None
    situacaoCompraNome: str | None = None
    usuarioNome: str | None = None


class AtaRegistroPrecoPeriodoDTO(BaseModel):
    numeroControlePNCPAta: str | None = None
    numeroAtaRegistroPreco: str | None = None
    anoAta: int | None = None
    numeroControlePNCPCompra: str | None = None
    cancelado: bool | None = None
    dataCancelamento: AwareDatetime | None = Field(None, examples=["2025-07-11T13:08:48"])
    dataAssinatura: AwareDatetime | None = Field(None, examples=["2025-07-11T13:08:48"])
    vigenciaInicio: AwareDatetime | None = Field(None, examples=["2025-07-11T13:08:48"])
    vigenciaFim: AwareDatetime | None = Field(None, examples=["2025-07-11T13:08:48"])
    dataPublicacaoPncp: AwareDatetime | None = Field(None, examples=["2025-07-11T13:08:48"])
    dataInclusao: AwareDatetime | None = Field(None, examples=["2025-07-11T13:08:48"])
    dataAtualizacao: AwareDatetime | None = Field(None, examples=["2025-07-11T13:08:48"])
    dataAtualizacaoGlobal: AwareDatetime | None = Field(None, examples=["2025-07-11T13:08:48"])
    usuario: str | None = None
    objetoContratacao: str | None = None
    cnpjOrgao: str | None = None
    nomeOrgao: str | None = None
    cnpjOrgaoSubrogado: str | None = None
    nomeOrgaoSubrogado: str | None = None
    codigoUnidadeOrgao: str | None = None
    nomeUnidadeOrgao: str | None = None
    codigoUnidadeOrgaoSubrogado: str | None = None
    nomeUnidadeOrgaoSubrogado: str | None = None


class PaginaRetornoAtaRegistroPrecoPeriodoDTO(BaseModel):
    data: list[AtaRegistroPrecoPeriodoDTO] | None = None
    totalRegistros: int | None = None
    totalPaginas: int | None = None
    numeroPagina: int | None = None
    paginasRestantes: int | None = None
    empty: bool | None = None


class PlanoContratacaoComItensDoUsuarioDTO(BaseModel):
    itens: list[PlanoContratacaoItemDTO] | None = None
    codigoUnidade: str | None = None
    nomeUnidade: str | None = None
    anoPca: int | None = None
    orgaoEntidadeRazaoSocial: str | None = None
    orgaoEntidadeCnpj: str | None = None
    dataPublicacaoPNCP: AwareDatetime | None = Field(None, examples=["2025-07-11T13:08:48"])
    dataAtualizacaoGlobalPCA: AwareDatetime | None = Field(None, examples=["2025-07-11T13:08:48"])
    idPcaPncp: str | None = None


class RecuperarCompraDTO(BaseModel):
    valorTotalEstimado: float | None = None
    valorTotalHomologado: float | None = None
    indicadorOrcamentoSigiloso: IndicadorOrcamentoSigiloso | None = None
    orcamentoSigilosoCodigo: int | None = None
    orcamentoSigilosoDescricao: str | None = None
    numeroControlePNCP: str | None = None
    linkSistemaOrigem: str | None = None
    linkProcessoEletronico: str | None = None
    anoCompra: int | None = None
    sequencialCompra: int | None = None
    numeroCompra: str | None = None
    processo: str | None = None
    orgaoEntidade: RecuperarOrgaoEntidadeDTO | None = None
    unidadeOrgao: RecuperarUnidadeOrgaoDTO | None = None
    orgaoSubRogado: RecuperarOrgaoEntidadeDTO | None = None
    unidadeSubRogada: RecuperarUnidadeOrgaoDTO | None = None
    modalidadeId: int | None = None
    modalidadeNome: str | None = None
    justificativaPresencial: str | None = None
    modoDisputaId: int | None = None
    modoDisputaNome: str | None = None
    tipoInstrumentoConvocatorioCodigo: int | None = None
    tipoInstrumentoConvocatorioNome: str | None = None
    amparoLegal: RecuperarAmparoLegalDTO | None = None
    objetoCompra: str | None = None
    informacaoComplementar: str | None = None
    srp: bool | None = None
    fontesOrcamentarias: list[ContratacaoFonteOrcamentariaDTO] | None = None
    dataPublicacaoPncp: AwareDatetime | None = Field(None, examples=["2025-07-11T13:08:48"])
    dataAberturaProposta: AwareDatetime | None = Field(None, examples=["2025-07-11T13:08:48"])
    dataEncerramentoProposta: AwareDatetime | None = Field(None, examples=["2025-07-11T13:08:48"])
    situacaoCompraId: SituacaoCompraId | None = None
    situacaoCompraNome: str | None = None
    existeResultado: bool | None = None
    dataInclusao: AwareDatetime | None = Field(None, examples=["2025-07-11T13:08:48"])
    dataAtualizacao: AwareDatetime | None = Field(None, examples=["2025-07-11T13:08:48"])
    dataAtualizacaoGlobal: AwareDatetime | None = Field(None, examples=["2025-07-11T13:08:48"])
    usuarioNome: str | None = None


class RecuperarContratoDTO(BaseModel):
    numeroControlePncpCompra: str | None = None
    codigoPaisFornecedor: str | None = None
    anoContrato: int | None = None
    tipoContrato: TipoContrato | None = None
    numeroContratoEmpenho: str | None = None
    dataAssinatura: date | None = None
    dataVigenciaInicio: date | None = None
    dataVigenciaFim: date | None = None
    niFornecedor: str | None = None
    tipoPessoa: TipoPessoa | None = None
    orgaoEntidade: RecuperarOrgaoEntidadeDTO | None = None
    categoriaProcesso: Categoria | None = None
    dataPublicacaoPncp: AwareDatetime | None = Field(None, examples=["2025-07-11T13:08:48"])
    dataAtualizacao: AwareDatetime | None = Field(None, examples=["2025-07-11T13:08:48"])
    sequencialContrato: int | None = None
    unidadeOrgao: RecuperarUnidadeOrgaoDTO | None = None
    informacaoComplementar: str | None = None
    processo: str | None = None
    unidadeSubRogada: RecuperarUnidadeOrgaoDTO | None = None
    orgaoSubRogado: RecuperarOrgaoEntidadeDTO | None = None
    nomeRazaoSocialFornecedor: str | None = None
    niFornecedorSubContratado: str | None = None
    nomeFornecedorSubContratado: str | None = None
    numeroControlePNCP: str | None = None
    receita: bool | None = None
    numeroParcelas: int | None = None
    numeroRetificacao: int | None = None
    tipoPessoaSubContratada: TipoPessoaSubContratada | None = None
    objetoContrato: str | None = None
    valorInicial: float | None = None
    valorParcela: float | None = None
    valorGlobal: float | None = None
    valorAcumulado: float | None = None
    dataAtualizacaoGlobal: AwareDatetime | None = Field(None, examples=["2025-07-11T13:08:48"])
    identificadorCipi: str | None = None
    urlCipi: str | None = None
    usuarioNome: str | None = None


class PaginaRetornoRecuperarContratoDTO(BaseModel):
    data: list[RecuperarContratoDTO] | None = None
    totalRegistros: int | None = None
    totalPaginas: int | None = None
    numeroPagina: int | None = None
    paginasRestantes: int | None = None
    empty: bool | None = None


class PaginaRetornoRecuperarCompraPublicacaoDTO(BaseModel):
    data: list[RecuperarCompraPublicacaoDTO] | None = None
    totalRegistros: int | None = None
    totalPaginas: int | None = None
    numeroPagina: int | None = None
    paginasRestantes: int | None = None
    empty: bool | None = None


class RecuperarAtaDTO(BaseModel):
    """A single ata-de-registro-de-preço entry from /v1/atas.

    Mirrors AtaRegistroPrecoPeriodoDTO from the PNCP OpenAPI spec.
    Most fields are optional to tolerate upstream partial responses,
    but ``numeroControlePNCPAta`` is REQUIRED because it's the
    canonical primary key. Without that guard, a mis-routed contratos
    page would validate (extra='allow' would absorb the rest) and
    flatten to a row with NULL PK, which the upsert would then use
    to overwrite live atas rows.
    """

    model_config = ConfigDict(extra="allow")

    numeroControlePNCPAta: str
    numeroAtaRegistroPreco: str | None = None
    anoAta: int | None = None
    numeroControlePNCPCompra: str | None = None
    cancelado: bool | None = None
    dataCancelamento: str | None = None
    dataAssinatura: str | None = None
    vigenciaInicio: str | None = None
    vigenciaFim: str | None = None
    dataPublicacaoPncp: str | None = None
    dataInclusao: str | None = None
    dataAtualizacao: str | None = None
    dataAtualizacaoGlobal: str | None = None
    usuario: str | None = None
    objetoContratacao: str | None = None
    cnpjOrgao: str | None = None
    nomeOrgao: str | None = None
    cnpjOrgaoSubrogado: str | None = None
    nomeOrgaoSubrogado: str | None = None
    codigoUnidadeOrgao: str | None = None
    nomeUnidadeOrgao: str | None = None
    codigoUnidadeOrgaoSubrogado: str | None = None
    nomeUnidadeOrgaoSubrogado: str | None = None


class PaginaRetornoPlanoContratacaoComItensDoUsuarioDTO(BaseModel):
    data: list[PlanoContratacaoComItensDoUsuarioDTO] | None = None
    totalRegistros: int | None = None
    totalPaginas: int | None = None
    numeroPagina: int | None = None
    paginasRestantes: int | None = None
    empty: bool | None = None


class ConsultarInstrumentoCobrancaDTO(BaseModel):
    cnpj: str | None = None
    ano: int | None = None
    sequencialContrato: int | None = None
    sequencialInstrumentoCobranca: int | None = None
    tipoInstrumentoCobranca: TipoInstrumentoCobrancaDTO | None = None
    numeroInstrumentoCobranca: str | None = None
    dataEmissaoDocumento: date | None = None
    observacao: str | None = None
    chaveNFe: str | None = None
    fonteNFe: int | None = None
    dataConsultaNFe: AwareDatetime | None = Field(None, examples=["2025-07-11T13:08:48"])
    statusResponseNFe: str | None = None
    jsonResponseNFe: str | None = None
    notaFiscalEletronica: NotaFiscalEletronicaConsultaDTO | None = None
    dataInclusao: AwareDatetime | None = Field(None, examples=["2025-07-11T13:08:48"])
    dataAtualizacao: AwareDatetime | None = Field(None, examples=["2025-07-11T13:08:48"])
    recuperarContratoDTO: RecuperarContratoDTO | None = None


class PaginaRetornoConsultarInstrumentoCobrancaDTO(BaseModel):
    data: list[ConsultarInstrumentoCobrancaDTO] | None = None
    totalRegistros: int | None = None
    totalPaginas: int | None = None
    numeroPagina: int | None = None
    paginasRestantes: int | None = None
    empty: bool | None = None
